### ISSUE TITLE
备案信息不显示

### ISSUE THREAD

**Issue by ym679** [jiewenhuang/halo-theme-joe3.0#105]
### 是什么版本出现了此问题？

1.1.2

### 发生了什么？

填写备案信息后不显示

**Comment by jiewenhuang** [comment]
<img width="647" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/c1989733-0536-482e-b7ab-46517bc080e4">

**Comment by ym679** [comment]
> <img alt="image" width="647" src="https://user-images.githubusercontent.com/68629578/271578032-c1989733-0536-482e-b7ab-46517bc080e4.png">

多谢
