### ISSUE TITLE
每次进入网站主页都要登录Halo账号

### ISSUE THREAD

**Issue by ACZSHOP** [jiewenhuang/halo-theme-joe3.0#110]
### 是什么版本出现了此问题？

1.1.3

### 在线站点地址

https://aczshop.top

### 发生了什么？

每次进入网站主页都要登录Halo账号,请取消它

### 附加信息

![lo](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/142337549/696e89b0-1dbd-4bfa-a999-b6ddeb4081e4)

**Comment by AGX5279** [comment]
今天虽然更新了，但依旧还在出现这个问题

**Comment by fanfanxhf** [comment]
> 目前在主页依旧弹出https://www.huicai.xyz

我是重启一下就好了
