### ISSUE TITLE
sitemap中的域名固定为localhost

### ISSUE THREAD

**Issue by hanfengyangzai** [jiewenhuang/halo-theme-joe3.0#113]
### 是什么版本出现了此问题？

1.1.0

### 在线站点地址

http://blog.51lvcn.cn/sitemap.xml

### 发生了什么？

你好，我的站点sitemap中域名不正确，是不是哪里设置的不对

**Comment by jiewenhuang** [comment]
看一下外部链接对不对，这个不是主题生成的，可以看下相关插件的仓库
