### ISSUE TITLE
轮播图设置希望能够选择固定标签文章

### ISSUE THREAD

**Issue by stars-one** [jiewenhuang/halo-theme-joe3.0#116]
### 描述一下此特性

目前轮播图设置需要手动查找文章标题,且没有模糊查询功能,比较难用

之前Joe2.0版本是提供选择某个标签的几个文章的,建议加个标签快速添加文章功能,预想效果:

> 点击按钮,先是出现标签列表,然后选择某个标签后,会将有该标签的全部文章批量添加到文章列表

另外一个建议优化: **添加文章的时候可以添加一个模糊的标题查询功能**

**Comment by jiewenhuang** [comment]
这个目前实现不了，不过支持自定义数据
