### ISSUE TITLE
文章侧边栏标签重合

### ISSUE THREAD

**Issue by story-x** [jiewenhuang/halo-theme-joe3.0#118]
### 是什么版本出现了此问题？

2.10.0

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/45375162/2255990a-563b-4f97-8740-5fc3da822171)

**Comment by jiewenhuang** [comment]
提供下在线地址和文章信息

**Comment by story-x** [comment]
> 提供下在线地址和文章信息

https://blog.potato.work/archives/srlink

**Comment by jiewenhuang** [comment]
> > 提供下在线地址和文章信息
> 
> https://blog.potato.work/archives/srlink

关闭toc插件，主题内置有，不需要插件

**Comment by TaCraft-Sociality** [comment]
> ### 是什么版本出现了此问题？
> 2.10.0
> 
> ### 在线站点地址
> _No response_
> 
> ### 发生了什么？
> ![image](https://user-images.githubusercontent.com/45375162/275142172-2255990a-563b-4f97-8740-5fc3da822171.png)
> 
> ### 相关日志输出
> _No response_
> 
> ### 附加信息
> _No response_

你最后是怎么更改的字体呢
