### ISSUE TITLE
博主信息名称链接指向localhost

### ISSUE THREAD

**Issue by yundabei** [jiewenhuang/halo-theme-joe3.0#123]
### 是什么版本出现了此问题？

 1.1.1

### 在线站点地址

https://qianduanlu.com/

### 发生了什么？

我是在1Panel面板一键部署的Halo,因要开启SSL,所以1Panel后台外部访问地址指向localhost,但是该主题获取到的不是真实域名而是localhost:8080

### 附加信息

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/34499405/b54e6a3d-a20c-40d4-aea5-c26325e312ae)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/34499405/135ed184-bd56-4c45-beb7-5b619568ee79)

**Comment by jiewenhuang** [comment]
1panel我用过，我不知道你开ssl和这个外部链接有什么联系，但是halo的外部链接填的就是你实际的访问链接，很多地方都是直接获取的外部链接，自行修改。

**Comment by yundabei** [comment]
好的
