### ISSUE TITLE
想问一下waline的设置在主题的哪块？

### ISSUE THREAD

**Issue by seazt** [jiewenhuang/halo-theme-joe3.0#124]
### 你当前使用的版本

1.1.4

### 描述一下此特性

想问一下waline的设置在主题的哪块？

**Comment by jiewenhuang** [comment]
<img width="1107" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/512a8aee-1ea0-4533-b951-a11b74fcb171">

**Comment by seazt** [comment]
非常感谢，已解决  注册到最后一步以为要在自定义里面手动添加代码。原来是在基本设置里面

**Comment by seazt** [comment]
你好 博主 还想问一下留言板页面 要怎么添加呀  ？ 万分感谢




seazt
***@***.***









                       
原始邮件
                       
                     

发件人："Jevon"< ***@***.*** &gt;;

发件时间：2023/10/28 13:47

收件人："jiewenhuang/halo-theme-joe3.0"< ***@***.*** &gt;;

抄送人："seazt"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [jiewenhuang/halo-theme-joe3.0] 想问一下waline的设置在主题的哪块？ (Issue #124)
