### ISSUE TITLE
你好博主想问一下，页面设置自定义模板为留言板，网站页面打不开的情况，是不是我设置有问题呀？

### ISSUE THREAD

**Issue by seazt** [jiewenhuang/halo-theme-joe3.0#125]
### 是什么版本出现了此问题？

1.1.4

### 在线站点地址

https://www.liuxiaopeng.cn/

### 发生了什么？

你好博主想问一下，页面设置自定义模板为留言板，网站页面打不开的情况，是不是我设置有问题呀？

### 附加信息

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139607779/15a5f082-5370-46aa-8ef2-7040526853b7)

**Comment by seazt** [comment]
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139607779/56c432b0-a8ee-44ca-9a2d-11d9bf314399)

**Comment by jiewenhuang** [comment]
提供下日志

**Comment by seazt** [comment]
最近一小时的日志&nbsp; 辛苦啦



seazt
***@***.***









                       
原始邮件
                       
                     

发件人："Jevon"< ***@***.*** &gt;;

发件时间：2023/10/29 23:59

收件人："jiewenhuang/halo-theme-joe3.0"< ***@***.*** &gt;;

抄送人："seazt"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [jiewenhuang/halo-theme-joe3.0] 你好博主想问一下，页面设置自定义模板为留言板，网站页面打不开的情况，是不是我设置有问题呀？ (Issue #125)




 
提供下日志

**Comment by seazt** [comment]
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139607779/a6dba235-5298-422d-a7f9-e84d29218bfc)

**Comment by jiewenhuang** [comment]
复现不了，尝试保存下所有设置，然后切换评论看看

**Comment by seazt** [comment]
你好博主  保存完所有配置还是500的错误  上面有我主题的网址 你看看

**Comment by seazt** [comment]
我评论切换成waline 就会出现上面的500的错误 不知道咋回事

**Comment by seazt** [comment]
用默认评论就好着呢

**Comment by jiewenhuang** [comment]
更新版本看看

**Comment by seazt** [comment]
版本更新为1.1.6，用了waline就打不开了，想问下博主 waline 你是用什么方式部署的？ 国内版还是国外版？

**Comment by jiewenhuang** [comment]
docker compose部署的，在国内。不行，提供下日志吧

**Comment by seazt** [comment]
主题里设置waline评论就报错，500打不开   用默认评论插件可以， 只有留言板打不开文章下面评论waline正常使用找好久了不知道咋回事。应该和主题有关
![278888970-a6dba235-5298-422d-a7f9-e84d29218bfc](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139607779/d02efc28-2f65-4013-be8b-2bbfec7d0728)

**Comment by seazt** [comment]
问题解决了  升级halo为最新版 2.10.2问题解决了，留言板能打开了   之前的版本是2.8.0
