### ISSUE TITLE
版权归属不能读取到文章是谁写的，不管是谁写的都显示为管理员的名字

### ISSUE THREAD

**Issue by TaCraft-Sociality** [jiewenhuang/halo-theme-joe3.0#126]

**Comment by jiewenhuang** [comment]
<img width="1123" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/aa9358ae-d90d-4e5a-b562-df786f69073b">
这边测试正常的，文章归属是否有多个用户？现在只获取第一个

**Comment by TaCraft-Sociality** [comment]
> <img alt="image" width="1123" src="https://user-images.githubusercontent.com/68629578/278958520-aa9358ae-d90d-4e5a-b562-df786f69073b.png"> 这边测试正常的，文章归属是否有多个用户？现在只获取第一个

多个,但是文章不是我创建的,也显示我就很奇怪,还有自定义字体没办法自定义本地字体文件吗
