### ISSUE TITLE
宽度大于1360px时内容显示错位

### ISSUE THREAD

**Issue by NormanZyq** [jiewenhuang/halo-theme-joe3.0#127]
### 是什么版本出现了此问题？

目前最新的1.1.4仍可复现。但1.0.8没有该问题

### 在线站点地址

https://zzbloc.top/

### 发生了什么？

宽屏下（宽度>1360px）所有页面无法正确显示，暂不清楚是我设置的问题还是什么设置引起的，这种情况会导致页面几乎不可用，如果不是bug而是设置问题，麻烦您帮忙下应该如何解决并close掉，感谢。

问题截图：
<img width="1379" alt="iShot_2023-10-30_11 44 49" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/32858941/fcc8f76f-bb44-4510-8566-a8536e4d74d7">

<img width="1365" alt="iShot_2023-10-30_11 45 07" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/32858941/9d04b734-a50d-4652-8656-21c2b87354e5">

之前我一直用的是1.0.8，有一次更新后（版本忘记了，但并非1.1.4，这中间的版本也存在该问题）遇到了此问题然后就回退到了1.0.8，现在更新到1.1.4仍然会遇到这个问题，为保证网站显示正常所以于是再次回退到了1.0.8。如有需要可以联系我将版本更新到1.1.4供您排查

**Comment by jiewenhuang** [comment]
v1.0.9修改了最大宽高的单位，release更新有写，更前看下记录。去基本设置，内容宽高重新设置一下即可
