### ISSUE TITLE
文章页末尾出现转瞬即逝的无关页面元素

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#129]
### 是什么版本出现了此问题？

1.1.4

### 发生了什么？

文章加载过程中/后，在文章的末尾会短暂地出现下图所示的页面元素，加载完毕之后消失
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/e0f737de-0d76-4049-abef-b45263a77a35)

**Comment by jiewenhuang** [comment]
这应该是点赞的按钮，这边无法复现，如果是一直在，提供下在线地址

**Comment by Einstein-schrodinger** [comment]
> 这应该是点赞的按钮，这边无法复现，如果是一直在，提供下在线地址
你的网站也会出现这种情况
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/c3207184-f5fa-41fa-88e3-e4e03e971d30)

**Comment by Einstein-schrodinger** [comment]
你把网速调慢一点试试，加载过程中才有，加载完毕就看不到了
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/7d0fce9a-f13c-44e6-8844-dd109b5f540c)
