### ISSUE TITLE
自定义侧边栏的内容

### ISSUE THREAD

**Issue by GuGuGee** [jiewenhuang/halo-theme-joe3.0#13]
是否有计划提供类似wordpress的自定义小工具，可以自己添加想要的内容在首页的侧边栏和文章详情页的侧边栏（比如图片、视频、二维码之类的）

<img src="https://img.laoda.de/i/2023/08/14/m4t7s4-0.webp" alt="image-20230814133831193" style="zoom:33%;" />

**Comment by jiewenhuang** [comment]
等halo-dev/halo#4603，现在还无法实现

**Comment by GuGuGee** [comment]
> 等[halo-dev/halo#4603](https://github.com/halo-dev/halo/issues/4603)，现在还无法实现

好像这个issue解决了！

**Comment by jiewenhuang** [comment]
基础已经完成，等后续添加组件
