### ISSUE TITLE
页脚云服务提供商格式显示BUG

### ISSUE THREAD

**Issue by Dion-Lee** [jiewenhuang/halo-theme-joe3.0#131]
### 是什么版本出现了此问题？

1.1.5

### 发生了什么？

<img width="308" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68332968/e9a3031f-cb2e-4d8c-853b-0aee9f419086">

**Comment by jiewenhuang** [comment]
？

**Comment by Dion-Lee** [comment]
> ？

logo换行了，包括文章内容页的版权归属信息也一样，logo单独cheng成一行
<img width="986" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68332968/ddf644eb-0f29-4979-bf8e-20a19f545fd1">

**Comment by jiewenhuang** [comment]
在线网址提供下？我这边好像没有这个问题的喔，是不是修改了什么

**Comment by Dion-Lee** [comment]
> 在线网址提供下？我这边好像没有这个问题的喔，是不是修改了什么

[blog.dlc.ink](https://blog.dlc.ink/)

**Comment by jiewenhuang** [comment]
![IMG_1090](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/6fae852b-ecdb-4aae-936c-8e5eec561fbd)
![IMG_1091](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/1efc36ff-c570-4489-9fb6-3b15b0fd3f8c)
我这边显示都是正常的喔

**Comment by Dion-Lee** [comment]
> ![IMG_1090](https://user-images.githubusercontent.com/68629578/281648943-6fae852b-ecdb-4aae-936c-8e5eec561fbd.png) ![IMG_1091](https://user-images.githubusercontent.com/68629578/281648969-1efc36ff-c570-4489-9fb6-3b15b0fd3f8c.jpeg) 我这边显示都是正常的喔

很奇怪，我换了电脑，换了网络，都是那样子。算了，就这样凑合吧

**Comment by jiewenhuang** [comment]
> > ![IMG_1090](https://user-images.githubusercontent.com/68629578/281648943-6fae852b-ecdb-4aae-936c-8e5eec561fbd.png) ![IMG_1091](https://user-images.githubusercontent.com/68629578/281648969-1efc36ff-c570-4489-9fb6-3b15b0fd3f8c.jpeg) 我这边显示都是正常的喔
> 
> 很奇怪，我换了电脑，换了网络，都是那样子。算了，就这样凑合吧

你可以看看是不是自己加了什么样式，或者改了什么导致文件引用不全

**Comment by Dion-Lee** [comment]
问题已解决，又拍云CDN设置了WebP 自适应导致的，关掉就好了
