### ISSUE TITLE
文章默认缩略图随机api调用建议

### ISSUE THREAD

**Issue by DragonYH** [jiewenhuang/halo-theme-joe3.0#136]
### 你当前使用的版本

1.1.6

### 描述一下此特性

默认缩略图栏填的是随机图片api（https://picsum.photos/350/200）
但实际加载出来后，所有文章缩略图都为同一个。
（看到8月份有人提了这个，标记为解决）

### 附加信息

api官方提示：
若要在浏览器中请求多个相同大小的图像，请添加查询参数以防止缓存图像：random
img src="https://picsum.photos/200/300?random=1"
img src="https://picsum.photos/200/300?random=2"

**Comment by jiewenhuang** [comment]
这不是api，就只是一个图片地址，当默认图片和文章图片都为空才加载随机图，随机图设置在基本设置那里。现在这个就只是默认图片
