### ISSUE TITLE
希望文章默认缩略图可以支持随机图的形式

### ISSUE THREAD

**Issue by ldwcool** [jiewenhuang/halo-theme-joe3.0#139]
### 描述一下此特性

主题设置 --> 设置 --> 文章默认缩略图 希望可以支持随机图的形式

### 附加信息

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139094465/63be07ca-c2ae-4648-99d4-5c6d8dba686a)

**Comment by jiewenhuang** [comment]
默认缩略图为空，且文章封面为空，则会调用基本设置那里的随机图api

**Comment by ldwcool** [comment]
好的，谢谢！
