### ISSUE TITLE
文章侧边栏目录悬浮

### ISSUE THREAD

**Issue by myname365** [jiewenhuang/halo-theme-joe3.0#14]
<img width="435" alt="图片" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/133751744/6ed8e4ea-f04d-4f00-a20a-fa5856f1cf50">
<img width="515" alt="图片" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/133751744/776c2a58-ea3c-4925-8723-25a2cad36c82">

**Comment by jiewenhuang** [comment]
能具体说明下，或者有在线链接吗？这边还没有遇到过

**Comment by myname365** [comment]
就是目录的位置异常
https://github.com/jiewenhuang/halo-theme-joe3.0/assets/133751744/d3dc47ae-ab91-4071-93cf-1960dbc8eefc

**Comment by jiewenhuang** [comment]
有在线地址吗？这边测试都是正常的，没有复现

**Comment by myname365** [comment]
已解决，不要安装这个插件
<img width="1192" alt="图片" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/133751744/1c2971e6-94ea-483a-a08a-c81b1ae7b27a">
