### ISSUE TITLE
侧栏归档，侧栏分类无法使用

### ISSUE THREAD

**Issue by WQHASH** [jiewenhuang/halo-theme-joe3.0#140]
### 描述一下此特性

以选中，**归档，分类，标签**，但现在**只有标签**展示效果

halo 版本： 2.10
电脑： win11

### 附加信息

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/26003488/fbbe41e3-e80b-4dd3-980a-858472dc033b)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/26003488/ee0c1795-b9fd-46fe-94fb-51085fcc6d76)

**Comment by jiewenhuang** [comment]
这是页面开关，显示什么内容要在侧边栏设置自行选择
