### ISSUE TITLE
waline评论的gif功能导致footer元素异常

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#141]
### 是什么版本出现了此问题？

1.1.6

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/5ccd13fe-d878-456f-aa85-35e78ddf8137)
如图所示点击gif后有两个问题：
1. gif位于footer下面，不美观
2. 点击gif后会撑开一段距离，使得footer会抬高（原本是在最下方的）

**Comment by Einstein-schrodinger** [comment]
建议：这gif图能否替换成国内的一些表情包

**Comment by yundabei** [comment]
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/34499405/111da327-c75c-4b8f-8b52-9d233009530c)
https://github.com/jiewenhuang/halo-theme-joe3.0/pull/152
