### ISSUE TITLE
首页缩略图随机功能

### ISSUE THREAD

**Issue by Aurora-Dylan** [jiewenhuang/halo-theme-joe3.0#142]
### 描述一下此特性

请问可以将首页的文章默认缩略图每一个都随机吗？
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/72263906/f8f85afc-2a6b-409e-9bc6-07c681999dbf)

就是四个图都是随机的不一样的图

**Comment by jiewenhuang** [comment]
see #139
