### ISSUE TITLE
随即图api没有生效

### ISSUE THREAD

**Issue by ZTfred** [jiewenhuang/halo-theme-joe3.0#144]
### 是什么版本出现了此问题？

 1.1.6

### 在线站点地址

https://alialili.cn/

### 发生了什么？

设置了随即图api，没有生效
api地址：https://api.likepoems.com/img/bing
可以直接访问成功的

### 附加信息

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/53425107/59b38dee-47f7-4579-a231-2eb2a37308a7)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/53425107/7be44d00-08ac-46b9-9886-a1d45042fb58)

**Comment by Einstein-schrodinger** [comment]
你可能改错地方了
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/ce911cb9-8a98-4c69-8a79-e3fb7a13c389)

**Comment by ZTfred** [comment]
> 你可能改错地方了 ![image](https://private-user-images.githubusercontent.com/62790820/285576069-ce911cb9-8a98-4c69-8a79-e3fb7a13c389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDQ0NTgsIm5iZiI6MTcwMDkwNDE1OCwicGF0aCI6Ii82Mjc5MDgyMC8yODU1NzYwNjktY2U5MTFjYjktOGE5OC00YzY5LThhNzktZTNmYjdhMTNjMzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA5MjIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjgwNmM5ZWVmNTQyZWU2NWRhYmUxYWExMzVhYTNhYmEzMmQ4NDAzMzE2NDNlZDU3NTdmOGQwYjRmNDIwYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XT351iWe3HXrVFFuUszXxqb7veO1xtLeDdnIb0NoE2E)

我是指定随机图api，文章默认加载随机图的

**Comment by Einstein-schrodinger** [comment]
> > 你可能改错地方了 ![image](https://private-user-images.githubusercontent.com/62790820/285576069-ce911cb9-8a98-4c69-8a79-e3fb7a13c389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDQ0NTgsIm5iZiI6MTcwMDkwNDE1OCwicGF0aCI6Ii82Mjc5MDgyMC8yODU1NzYwNjktY2U5MTFjYjktOGE5OC00YzY5LThhNzktZTNmYjdhMTNjMzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA5MjIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjgwNmM5ZWVmNTQyZWU2NWRhYmUxYWExMzVhYTNhYmEzMmQ4NDAzMzE2NDNlZDU3NTdmOGQwYjRmNDIwYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XT351iWe3HXrVFFuUszXxqb7veO1xtLeDdnIb0NoE2E)
> 
> 我是指定随机图api，文章默认加载随机图的

那可能你得把文章默认缩略图那里的网址删掉？

**Comment by jiewenhuang** [comment]
see #139
