### ISSUE TITLE
配置了菜单图标但未显示

### ISSUE THREAD

**Issue by seazt** [jiewenhuang/halo-theme-joe3.0#145]
### 是什么版本出现了此问题？

1.1.6

### 在线站点地址

https://www.liuxiaopeng.cn/

### 发生了什么？

配置了菜单图标但未显示

### 附加信息

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139607779/4e77e4e9-c33b-4b5c-9e61-614377695305)

**Comment by seazt** [comment]
页面未生成那个class 不知道哪块出了问题
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139607779/24916e1b-831b-4940-aae5-aca1477f4f46)

**Comment by jiewenhuang** [comment]
主题设置那里有个开关，看下开了没有，默认关闭的

**Comment by seazt** [comment]
找到了 已经解决
