### ISSUE TITLE
图库显示跨域请求

### ISSUE THREAD

**Issue by seazt** [jiewenhuang/halo-theme-joe3.0#146]
### 是什么版本出现了此问题？

1.1.6

### 发生了什么？

图库显示跨域请求

### 附加信息

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139607779/5c089960-8976-4867-9ddb-d4813df5823e)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139607779/e27d36bd-d956-496b-aea4-59e3eaa4038e)

**Comment by jiewenhuang** [comment]
自行保持外部链接地址为实际访问地址，或者将请求域名加入白名单，具体自行搜索跨域问题解决。
