### ISSUE TITLE
建议添加广告位

### ISSUE THREAD

**Issue by ACZSHOP** [jiewenhuang/halo-theme-joe3.0#151]
### 你当前使用的版本

1.1.6

### 描述一下此特性

类似于JOE2.0的广告配置（侧边栏 + 文章页）
主题源码https://github.com/qinhua/halo-theme-joe2.0

**Comment by jiewenhuang** [comment]
<img width="1224" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/3ecbfa26-2a4e-4d5f-9b96-d77203c2b449">
这不是已经存在的吗

**Comment by ACZSHOP** [comment]
> <img alt="image" width="1224" src="https://private-user-images.githubusercontent.com/68629578/287457640-3ecbfa26-2a4e-4d5f-9b96-d77203c2b449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MzQ1NzEsIm5iZiI6MTcwMTUzNDI3MSwicGF0aCI6Ii82ODYyOTU3OC8yODc0NTc2NDAtM2VjYmZhMjYtMmE0ZS00ZDVmLTliOTYtZDc3MjAzYzJiNDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE2MjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZmM0NjlmMGFiZWVkY2VjNjlkMDZjMzVlZTYxNGQ1NWYzNzE2ZDliMTM2NDMwNTg3YWZmZDc5NWZlZmQ4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hdFoOJhZxgrfjM8ykvC_xMDDV2JHo68zY1GOrn5se4I">这不是已经存在的吗

原来是我没更新
