### ISSUE TITLE
文章不显示附件上传的本地图片

### ISSUE THREAD

**Issue by lizhengxing1993** [jiewenhuang/halo-theme-joe3.0#157]
### 是什么版本出现了此问题？

halo版本 2.11.1 ，数据库 MySQL Community Server - GPL / 8.1.0

### 在线站点地址

http://47.254.43.129:8080/archives/1702100814449

### 发生了什么？

文章内无法显示图片，使用的是附件上传方式，图片在本地

### 附加信息

![1702101219282](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/35167198/af262771-8624-4fd6-a659-6b096bc56e8b)

**Comment by jiewenhuang** [comment]
自行检查附件中图片是否正常显示
