### ISSUE TITLE
启用了主题的Waline评论

### ISSUE THREAD

**Issue by Stonewalling** [jiewenhuang/halo-theme-joe3.0#159]
### 是什么版本出现了此问题？

 1.1.6

### 在线站点地址

https://blog.micromatrix.cf/

### 发生了什么？

文章里评论了，但是侧边栏的评论数量不更新。我是用的Waline评论系统

**Comment by jiewenhuang** [comment]
fixed at v1.1.7

**Comment by Stonewalling** [comment]
> fixed at v1.1.7

更新之后为1.1.7版本，之前的评论数已经不显示
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/21361701/a12cc076-2902-4711-961a-e143b9e7276d)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/21361701/f4a230c1-31f8-4b90-bde0-5320deaf6cfd)

**Comment by jiewenhuang** [comment]
> > fixed at v1.1.7
> 
> 更新之后为1.1.7版本，之前的评论数已经不显示 ![image](https://private-user-images.githubusercontent.com/21361701/291032229-a12cc076-2902-4711-961a-e143b9e7276d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3OTcyMjMsIm5iZiI6MTcwMjc5NjkyMywicGF0aCI6Ii8yMTM2MTcwMS8yOTEwMzIyMjktYTEyY2MwNzYtMjkwMi00NzExLTk2MWEtZTE0M2I5ZTcyNzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA3MDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZmIyYTkyZGUyNzU4MTM0OWVjNzYwNGNlY2NiZDMzY2NlODFlNTk3ZTY4MDU5ZjQ0YTdlODZmMDlhODU1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.16gE0ChGhP6UvlUZ52DsPJkMPTvgxJEsCuqet670Z6E) ![image](https://private-user-images.githubusercontent.com/21361701/291032230-f4a230c1-31f8-4b90-bde0-5320deaf6cfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3OTcyMjMsIm5iZiI6MTcwMjc5NjkyMywicGF0aCI6Ii8yMTM2MTcwMS8yOTEwMzIyMzAtZjRhMjMwYzEtMzFmOC00YjkwLWJkZTAtNTMyMGRlYWY2Y2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA3MDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOThkYjQ0MjY4NGI4MTc5YWJjZTg1MTdkNDE5YTI3ZWFiZTQyY2Q2ZmM5Y2YzZjk2ZWFkYTRkMzk2MzFkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yaaIZDzkw-tHnvmN-fbV5pj5ou4YB6OayPWtpy8w_ZI)

<img width="359" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/7f1f0a8f-d1c2-44fc-970d-4293d326a0e4">
？，更新前看下更新说明，如果是因为unpkg的问题，就替换下资源地址。

**Comment by Stonewalling** [comment]
> > > fixed at v1.1.7
> > 
> > 
> > 更新之后为1.1.7版本，之前的评论数已经不显示 ![image](https://private-user-images.githubusercontent.com/21361701/291032229-a12cc076-2902-4711-961a-e143b9e7276d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3OTcyMjMsIm5iZiI6MTcwMjc5NjkyMywicGF0aCI6Ii8yMTM2MTcwMS8yOTEwMzIyMjktYTEyY2MwNzYtMjkwMi00NzExLTk2MWEtZTE0M2I5ZTcyNzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA3MDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZmIyYTkyZGUyNzU4MTM0OWVjNzYwNGNlY2NiZDMzY2NlODFlNTk3ZTY4MDU5ZjQ0YTdlODZmMDlhODU1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.16gE0ChGhP6UvlUZ52DsPJkMPTvgxJEsCuqet670Z6E) ![image](https://private-user-images.githubusercontent.com/21361701/291032230-f4a230c1-31f8-4b90-bde0-5320deaf6cfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3OTcyMjMsIm5iZiI6MTcwMjc5NjkyMywicGF0aCI6Ii8yMTM2MTcwMS8yOTEwMzIyMzAtZjRhMjMwYzEtMzFmOC00YjkwLWJkZTAtNTMyMGRlYWY2Y2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA3MDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOThkYjQ0MjY4NGI4MTc5YWJjZTg1MTdkNDE5YTI3ZWFiZTQyY2Q2ZmM5Y2YzZjk2ZWFkYTRkMzk2MzFkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yaaIZDzkw-tHnvmN-fbV5pj5ou4YB6OayPWtpy8w_ZI)
> 
> <img alt="image" width="359" src="https://private-user-images.githubusercontent.com/68629578/291033365-7f1f0a8f-d1c2-44fc-970d-4293d326a0e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzU5ODksIm5iZiI6MTcwMjg3NTY4OSwicGF0aCI6Ii82ODYyOTU3OC8yOTEwMzMzNjUtN2YxZjBhOGYtZDFjMi00NGZjLTk3MGQtNDI5M2QzMjZhMGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA1MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhN2I4MzkxZGY2MGJmMzRhOTBiMGQ0ZDQyNWJlZjM3NGVjNzZmNGU3ODcxN2Q5OWIzNWJmODc1MDk5MzQyMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QU9xIVHokW77DZWo2R4H9H4KEBPF9mXuAwNdv_UzciQ"> ？，更新前看下更新说明，如果是因为unpkg的问题，就替换下资源地址。

大佬具体怎么看啊，我在服务器上使用curl 设置里面的waline的一些地址，都是可以请求到的，https://unpkg.com的地址会出现一个重定向。是这个导致的吗
