### ISSUE TITLE
500 服务器内部错误

### ISSUE THREAD

**Issue by erruicoders** [jiewenhuang/halo-theme-joe3.0#16]
后台主题相关配置已全部保存，halo版本2.8，主题版本1.0.4，下面为报错日志
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/75353639/793eb91c-5760-4c6d-b4cc-e58aa1677558)

**Comment by jiewenhuang** [comment]
添加轮播图看看

**Comment by erruicoders** [comment]
> 添加轮播图看看

500 解决了，但是现在发现文章的封面不显示
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/75353639/7de716c7-3cc0-4bc9-8fa3-634b7fbd5424)

**Comment by jiewenhuang** [comment]
检查下文章有没有图片，然后看一下网络这次吗，现在显示的是懒加载图，而且没有文章封面也应该会出现默认图的

**Comment by erruicoders** [comment]
> 检查下文章有没有图片，然后看一下网络这次吗，现在显示的是懒加载图，而且没有文章封面也应该会出现默认图的

都有设置封面的，封面图片格式为webp，在其他主题下是可以显示的

**Comment by jiewenhuang** [comment]
有在线地址吗？或者封面图提供下，还有，文章列表那里封面图有显示吗？

**Comment by erruicoders** [comment]
> 有在线地址吗？或者封面图提供下，还有，文章列表那里封面图有显示吗？

https://img.errui.top/i/2023/08/04/iw1k34.webp
这是封面链接
轮播图和文章列表都不显示

**Comment by jiewenhuang** [comment]
<img width="941" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/18cea478-eebf-40f8-be25-fc5a14ec82ba">
我这边测试是没有问题的喔，看看你那边网络能正常访问图片吗

**Comment by erruicoders** [comment]
> <img alt="image" width="941" src="https://user-images.githubusercontent.com/68629578/260610934-18cea478-eebf-40f8-be25-fc5a14ec82ba.png"> 我这边测试是没有问题的喔，看看你那边网络能正常访问图片吗

浏览器是能打开的，但是主题内就不显示了

**Comment by jiewenhuang** [comment]
有在线地址吗？

**Comment by erruicoders** [comment]
> 有在线地址吗？

https://blog.errui.cc
看了下F12没有请求图片资源，后台不需要做什么设置吧

**Comment by erruicoders** [comment]
这是首页的三篇文章，封面并不显示
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/75353639/20bcf904-bc46-4713-b413-139fd85af5e1)
从顶栏的 专栏>后端开发 进入竟然有两张显示了
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/75353639/0b63a616-d366-47ed-b604-072fc5c30f19)

**Comment by jiewenhuang** [comment]
你是不是用了其他懒加载插件？

**Comment by erruicoders** [comment]
> 

好像是有的 ，我看下

**Comment by erruicoders** [comment]
> 你是不是用了其他懒加载插件？

确实是，解决啦，谢谢谢谢
