### ISSUE TITLE
搜索按钮无法点击，console报错了

### ISSUE THREAD

**Issue by huasio** [jiewenhuang/halo-theme-joe3.0#161]
### 是什么版本出现了此问题？

latest

### 在线站点地址

https://biontai.com

### 发生了什么？

搜索按钮无法点击，console报错了
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/23445537/2105dba4-2f44-4207-8948-eea88f2a0497)

**Comment by yundabei** [comment]
站点防火墙拦截太猛了
