### ISSUE TITLE
更换主题后css样式加载不出来导致网站显示慢

### ISSUE THREAD

**Issue by zh-Littlebird** [jiewenhuang/halo-theme-joe3.0#168]
### 是什么版本出现了此问题？

2.10.2

### 在线站点地址

geekscribe.cn

### 发生了什么？

waline加载慢导致网页显示特别慢，挂上梯子反应迅速！
![微信图片_20231215230913](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/50728951/4b0250b4-d551-4212-b3b2-e21b53f89442)

**Comment by jiewenhuang** [comment]
unpkg死了，1,1,7版本可以自定义资源地址
