### ISSUE TITLE
移动端toc按钮icon不显示

### ISSUE THREAD

**Issue by Litbay** [jiewenhuang/halo-theme-joe3.0#17]
halo 2.8；Joe3.0 1.0.4
如图所示，开启移动端toc后，按钮的icon不显示
![icon不显示](https://img.gugu.ovh/i/2023/08/15/kedy0z.webp)

**Comment by jiewenhuang** [comment]
有在线地址吗

**Comment by Litbay** [comment]
> 有在线地址吗

baihub.cn
