### ISSUE TITLE
轮播图默认图片死活改不了

### ISSUE THREAD

**Issue by loks666** [jiewenhuang/halo-theme-joe3.0#171]
### 是什么版本出现了此问题？

1.1.7

### 在线站点地址

https://code.superxiang.com/

### 发生了什么？

我配置了文章的轮播，然后想改变轮播图的默认图片，不管是在主题设置里，还是halo设置里，都没有相关的配置，想了解下这个图到底是在哪里设置？？？？

**Comment by loks666** [comment]
已解决

**Comment by bluezsd** [comment]
> 已解决

怎么解决的哦？我也遇到这个问题了

**Comment by loks666** [comment]
把链接设置为自定义的就行
