### ISSUE TITLE
页脚中的公安备案跳转url不会携带备案号

### ISSUE THREAD

**Issue by 52lemon6** [jiewenhuang/halo-theme-joe3.0#172]
### 是什么版本出现了此问题？

1.1.7

### 发生了什么？

1，页脚的公安备案号url链接跳转不会携带备案号，（公安貌似会判定为不合格）
2，跳转到的公安备案地址已是旧地址了，新地址已变更至https://beian.mps.gov.cn/#/query/webSearch?code=纯数字的公安备案号

**Comment by jiewenhuang** [comment]
？真的吗，为什么我看腾讯 阿里的网备也没有带

**Comment by 52lemon6** [comment]
> ？真的吗，为什么我看腾讯 阿里的网备也没有带

快去举报他（doge
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/40059643/b39b4fff-1919-4901-881d-38bce6c3e24c)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/40059643/33aaf531-eced-457e-8744-b0e47fc12b59)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/40059643/2cbd18b9-0ded-427d-8d8d-a21381a5c602)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/40059643/40a58b19-0abb-4b83-8f58-7f52a627a4fb)
