### ISSUE TITLE
更新1.1.7后无法访问，提示500|服务器内部错误

### ISSUE THREAD

**Issue by AshinLin** [jiewenhuang/halo-theme-joe3.0#174]
### 是什么版本出现了此问题？

2.11.2

### 发生了什么？

从主题商店更新了1.1.7，而后网站前台无法访问，更换其他主题没问题
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/13843885/3ebcf7b3-7661-43ef-9ff8-d36415b11e93)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/13843885/0ddfac43-46e8-4822-85ca-26ec70b05dd6)

**Comment by jiewenhuang** [comment]
看，更新说明，该保存的保存一遍。如果还有问题，提供log
