### ISSUE TITLE
兼容搜索框暗黑模式

### ISSUE THREAD

**Issue by wxyShine** [jiewenhuang/halo-theme-joe3.0#175]
### 描述一下此特性

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/42802152/03ee8a03-519d-453c-a632-af8925f35fb8)

**Comment by Einstein-schrodinger** [comment]
也希望能够适配自定义字体

**Comment by jiewenhuang** [comment]
字体等待插件更新
