### ISSUE TITLE
侧边栏添加图片显示模块（原二维码模块）后首页显示500错误

### ISSUE THREAD

**Issue by bluezsd** [jiewenhuang/halo-theme-joe3.0#176]
### 是什么版本出现了此问题？

1.17

### 发生了什么？

侧边栏添加图片显示模块（原二维码模块）后显示500错误
侧边栏添加网站公告模块也是一样会500错误

**Comment by jiewenhuang** [comment]
<img width="1467" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/210fd481-3625-438c-9c0f-c86b44977b15">
？Halo版本？

**Comment by bluezsd** [comment]
> <img alt="image" width="1467" src="https://private-user-images.githubusercontent.com/68629578/291541677-210fd481-3625-438c-9c0f-c86b44977b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzkyNjIsIm5iZiI6MTcwMjk3ODk2MiwicGF0aCI6Ii82ODYyOTU3OC8yOTE1NDE2NzctMjEwZmQ0ODEtMzYyNS00MzhjLTljMGYtYzg2YjQ0OTc3YjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA5NDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwM2U3ZjBkNGRhYzZjNjU2ZDQ4MWJjYTUyYmFhMTc4NTZjZDA3NGViMzk1MDE4YzQwODQ5M2M3MjQzYWRmMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NPIHODk0dNB4L0yOavA0M3n6R0GT5Vf29JRC-lJAggU"> ？Halo版本？

Halo2.11.2

**Comment by bluezsd** [comment]
我重启了一下docker，就可以了。可能是缓存的问题
