### ISSUE TITLE
希望新增Twikoo和Artalk评论系统~

### ISSUE THREAD

**Issue by Miykah** [jiewenhuang/halo-theme-joe3.0#177]
### 描述一下此特性

希望新增Twikoo和Artalk评论系统~

**Comment by backunderstar** [comment]
同希望新增twikoo，谢谢作者

**Comment by jiewenhuang** [comment]
第三方维护起来比较麻烦，而且官方评论也比较健全了。不会再新加其他评论了

**Comment by ruibaby** [comment]
目前应用市场已经有了 [Artalk](https://www.halo.run/store/apps/app-mBoYu)、[Waline](https://www.halo.run/store/apps/app-lggDh)、[Twikoo](https://www.halo.run/store/apps/app-FgtLY) 插件，可以无入侵的集成三方评论系统。

此外，集成三方评论系统也不推荐在主题实现，建议将此主题的三方评论标记为过时。
