### ISSUE TITLE
关于文章略缩图的问题

### ISSUE THREAD

**Issue by lslove10010** [jiewenhuang/halo-theme-joe3.0#178]
### 你当前使用的版本

halo2.11,JOE3.0

### 描述一下此特性

首先感谢大佬的主题，非常适合我这样的小白，想反馈的就是按照测试，使用随机api文章略缩图的话，每篇文章的图片都一样，大佬是否有办法让略缩图自动随机，不重复

### 附加信息

![屏幕截图 2023-12-21 232938](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/96574438/0763ea85-3662-4a40-8f96-21413084dc0c)

**Comment by jiewenhuang** [comment]
基本设置那里有api设置，默认图为空时使用，逻辑是，文章封面>默认封面>随机图
