### ISSUE TITLE
代码复制无效，且与插件ToolBench冲突导致代码格式错误。

### ISSUE THREAD

**Issue by NikoYomi** [jiewenhuang/halo-theme-joe3.0#179]
### 是什么版本出现了此问题？

1.0.6

### 在线站点地址

https://snty.de

### 发生了什么？

目前遇到的问题如下：
1.开启插件ToolBench导致代码格式错误。
2.代码块旁边的复制点击无效。

在关闭后，格式错误的问题消失，但复制无效仍然存在。
按照#95打开语言也是复制无效。
所使用的主题为
theme-Joe3 1.0.6

问题一错误图何详情如下：
https://github.com/halo-dev/docs/issues/297

**Comment by jiewenhuang** [comment]
提供下在线网址，toolbench问题等作者解决，或者用md编辑器，或者试试插入html那个插件

**Comment by jiewenhuang** [comment]
<img width="1427" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/08598e5e-0ca7-48e8-8e3c-fc5f4f41e88a">
从提供的网站来看，并没有填入代码块语言。
正确应为，md  
<img width="373" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/672c28a0-8e7b-4a1a-a309-b4c46bc5c479">  
富文本  
<img width="628" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/1dcf9dd9-525c-4cd3-bcf7-f66d6e9ae91b">  
最后结果：  
<img width="1287" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/c64c1f53-c29a-4159-88e0-c1333736e716">

**Comment by NikoYomi** [comment]
> <img alt="image" width="1427" src="https://private-user-images.githubusercontent.com/68629578/292495613-08598e5e-0ca7-48e8-8e3c-fc5f4f41e88a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyOTU0MTcsIm5iZiI6MTcwMzI5NTExNywicGF0aCI6Ii82ODYyOTU3OC8yOTI0OTU2MTMtMDg1OThlNWUtMGNhNy00OGU4LThlM2MtZmM1ZjRmNDFlODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDAxMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzM2E3NGQwOGRiODQ2ZTQ2NDExZmY5YmJmMWFlYTUwNWRjNDg0N2FiMDZmYjQzYjc4YTlhZTBkYzA4ZGFmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YF7Hm8VNu7DdN_17YXaxBamHlrk_UJ_MZp_96chpPs4"> 从提供的网站来看，并没有填入代码块语言。 正确应为，md <img alt="image" width="373" src="https://private-user-images.githubusercontent.com/68629578/292495893-672c28a0-8e7b-4a1a-a309-b4c46bc5c479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyOTU0MTcsIm5iZiI6MTcwMzI5NTExNywicGF0aCI6Ii82ODYyOTU3OC8yOTI0OTU4OTMtNjcyYzI4YTAtOGU3Yi00YTFhLWEzMDktYjRjNDZiYzVjNDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDAxMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MWEyNWQ1ZTY2YTJlYWVjYWFlZmU4NDViNmYwNTYzNTdlMTEwM2I3NDJjMDFmN2I0Y2NjNWNlNWQyMTQ1ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vM04EJ1o3P4EkgizSTPlIB-9zeNLg5TWFLkmzxerdGE"> 富文本 <img alt="image" width="628" src="https://private-user-images.githubusercontent.com/68629578/292496083-1dcf9dd9-525c-4cd3-bcf7-f66d6e9ae91b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyOTU0MTcsIm5iZiI6MTcwMzI5NTExNywicGF0aCI6Ii82ODYyOTU3OC8yOTI0OTYwODMtMWRjZjlkZDktNTI1Yy00Y2QzLWJjZjctZjY2ZDZlOWFlOTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDAxMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZjhhMmNjNjg3M2JmMzNjNGJlODk2N2Q4YTgyNGRjYTUyZDA5YWRhY2FiMGM5MGZhMWRhYThkNWEyNjFkYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KEvqH9y1N9tBFOVh4Vqg8ZBBY7zzTdIeSzFc6_0dhJs"> 最后结果： <img alt="image" width="1287" src="https://private-user-images.githubusercontent.com/68629578/292496282-c64c1f53-c29a-4159-88e0-c1333736e716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyOTU0MTcsIm5iZiI6MTcwMzI5NTExNywicGF0aCI6Ii82ODYyOTU3OC8yOTI0OTYyODItYzY0YzFmNTMtYzI5YS00MTU5LTg4ZTAtYzEzMzM3MzZlNzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDAxMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNTVjMDZlYmNmNzQ3MmUwNTgyYmM3NzNhNWE0OTA4ZDI2MDNjNjk3NWQwYzA5YjNlZTljZGJjYTk4NDI0NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t34E_YsIPDr8FejevtaKJvg3v-L9x3igtrh8LmrRT0Y">

怎么填入代码块语言呢？并没有看到有对应的选项。是需要在文章代码块开头填写吗？

**Comment by jiewenhuang** [comment]
嗯，已知问题，后续再看看怎么解决
