### ISSUE TITLE
友链页评论邮件通知失效  求帮助

### ISSUE THREAD

**Issue by Miykah** [jiewenhuang/halo-theme-joe3.0#180]
### 是什么版本出现了此问题？

2.11.2

### 发生了什么？

友链页评论的邮件通知失效。 已测试过其他页面，邮件通知功能正常。请求帮助，谢谢大佬

**Comment by jiewenhuang** [comment]
新建页面，选择友联模板，不用自带的links

**Comment by Miykah** [comment]
> 新建页面，选择友联模板，不用自带的links

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/94845288/05fc33e0-67d9-4dfe-aca1-a08bb57fe7fe)

新建页面，如果别名取links，邮件通知仍然会失效。

换成其他别名，邮件通知功能正常，但是，主题模板中的links.html自定义修改的内容就不生效了。

**Comment by jiewenhuang** [comment]
页面内容上写就行了，比在设置那里写方便很多
