### ISSUE TITLE
【功能增强】博主信息社交版本加个微信吧

### ISSUE THREAD

**Issue by z-hanzhe** [jiewenhuang/halo-theme-joe3.0#182]
### 你当前使用的版本

 1.1.7

### 描述一下此特性

如题，博主信息社交版本加个微信吧

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/58802604/00710ef9-b368-453a-bfee-acafd5f3b2d3)

**Comment by wxyShine** [comment]
建议直接加个自定义

**Comment by jiewenhuang** [comment]
> 建议直接加个自定义

<img width="760" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/2da21c5f-3d7b-4da7-91e1-b1dba8fcd5bf">
踢出去

**Comment by z-hanzhe** [comment]
> 建议直接加个自定义

图标不知道哪里搞....

**Comment by wxyShine** [comment]
> > 建议直接加个自定义
> 
> 图标不知道哪里搞....

baidu.com

**Comment by z-hanzhe** [comment]
> > > 建议直接加个自定义
> > 图标不知道哪里搞....
> baidu.com

方便给个思路？？

**Comment by wxyShine** [comment]
> > > > 建议直接加个自定义
> > > 
> > > 
> > > 图标不知道哪里搞....
> > 
> > 
> > baidu.com baidu.com
> 
> 方便给个思路？？


![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/42802152/7810c499-ad39-45c4-87bc-c25ad8e5d7ca)

**Comment by z-hanzhe** [comment]
> ![image](https://private-user-images.githubusercontent.com/42802152/292810776-7810c499-ad39-45c4-87bc-c25ad8e5d7ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzQwNTksIm5iZiI6MTcwMzU3Mzc1OSwicGF0aCI6Ii80MjgwMjE1Mi8yOTI4MTA3NzYtNzgxMGM0OTktYWQzOS00NWM0LTg3YmMtYzI1YWQ4ZTVkN2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA2NTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTAxOTJkMzdjN2RiM2U2MzAyZDFjNTNiMWRiNzFiNzgwNjA1ZGFkY2U0N2MxNGRiZTgxMDk3Y2JiYzFjODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4DdbPj_mc3wrM0MOvFx5Kaj4qgShJ-xatGBwPt0xAec)

我想要的不是这种思路😅，不过我已经实现功能了，谢谢
