### ISSUE TITLE
【移植需求】Joe的通知功能

### ISSUE THREAD

**Issue by z-hanzhe** [jiewenhuang/halo-theme-joe3.0#183]
### 你当前使用的版本

1.1.7

### 描述一下此特性

希望能将Joe的通知功能移过来，这个功能很实用

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/58802604/48b0b372-8a85-4327-a52c-911a77d25307)

![screenshots](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/58802604/b1c95b11-62cf-4fed-82a6-b8419a619c07)

**Comment by jiewenhuang** [comment]
<img width="1066" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/fc3468b1-5e6a-4b05-91bb-5bb3834ec545">
