### ISSUE TITLE
设置网易云歌单不显示，非私密歌单

### ISSUE THREAD

**Issue by XM2510136957** [jiewenhuang/halo-theme-joe3.0#184]
### 是什么版本出现了此问题？

1.1.7

### 发生了什么？

设置网易云歌单不显示，非私密歌单。
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/18229485/0cdc8ca0-8844-4631-825b-3a095b953654)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/18229485/cffe7b46-fcaa-4a32-b3c2-bdd0b51ee9a3)

**Comment by hangyubin** [comment]
同样的问题！我解决了，在设置里，代码注入全局head标签填写 <link rel="stylesheet" href="/themes/theme-Joe3/assets/lib/APlayer/APlayer.min.css">
        <script src="/themes/theme-Joe3/assets/lib/APlayer/APlayer.min.js"></script>
        <script src="/themes/theme-Joe3/assets/lib/meting/meting.min.js"></script>搞定

**Comment by XM2510136957** [comment]
> 同样的问题！我解决了，在设置里，代码注入全局head标签填写
> 
> ![screenshot20231230](https://private-user-images.githubusercontent.com/25428613/293435219-231d38a0-c0a7-47fe-abd1-989330509cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzU5NDksIm5iZiI6MTcwMzkzNTY0OSwicGF0aCI6Ii8yNTQyODYxMy8yOTM0MzUyMTktMjMxZDM4YTAtYzBhNy00N2ZlLWFiZDEtOTg5MzMwNTA5Y2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDExMjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YzdkNmVhNjhiN2NiNGYyNjE4ZWFiOGYzZmFmNjg0NWJjMzBmM2Y5Y2JjODMxYzI4NjIyNDgxYzliZDQ5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OTPCXElEsOLq8P88O1ejA9rpuqNZ5WF2TTG7ZcfbOts)
> 
> 搞定
> 
> 
> same question！I解决了，在设置里，代码输入到全局头标签中
> 
> ![screenshot20231230](https://private-user-images.githubusercontent.com/25428613/293435219-231d38a0-c0a7-47fe-abd1-989330509cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzU5NDksIm5iZiI6MTcwMzkzNTY0OSwicGF0aCI6Ii8yNTQyODYxMy8yOTM0MzUyMTktMjMxZDM4YTAtYzBhNy00N2ZlLWFiZDEtOTg5MzMwNTA5Y2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDExMjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YzdkNmVhNjhiN2NiNGYyNjE4ZWFiOGYzZmFmNjg0NWJjMzBmM2Y5Y2JjODMxYzI4NjIyNDgxYzliZDQ5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OTPCXElEsOLq8P88O1ejA9rpuqNZ5WF2TTG7ZcfbOts)
> 
> 搞定

能发下代码嘛，图片不好复制！
