### ISSUE TITLE
看板娘关闭后，再次点击无法弹出

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#185]
### 是什么版本出现了此问题？

1.1.7

### 发生了什么？

1.看板娘关闭后点击按钮无法再次弹出
2.首页以及底部footer会遮挡看板娘按钮
首页遮挡
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/c74cd1e3-d616-41fd-87bf-41e113437165)
底部footer遮挡
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/fc47a513-62b0-4746-868d-96e6b8d9012a)

**Comment by jiewenhuang** [comment]
这个应该跟插件提，提高看板娘的z-index层级，或者自行手动注入  
```css
#live2d-toggle {
  z-index:99;
}
```
