### ISSUE TITLE
页脚访问量等错误

### ISSUE THREAD

**Issue by happy-Z** [jiewenhuang/halo-theme-joe3.0#189]
### 是什么版本出现了此问题？

最新版

### 在线站点地址

https://blog.czpv.top/

### 发生了什么？

访问量等为0

### 附加信息

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/58432632/13508dde-e19d-427f-97a1-554350bfd583)

**Comment by jiewenhuang** [comment]
不蒜子噶了，现在已经=恢复了
