### ISSUE TITLE
希望可以抄一下 `halo-theme-joe2.0` 的轮播图

### ISSUE THREAD

**Issue by FaithAluten** [jiewenhuang/halo-theme-joe3.0#194]
### 你当前使用的版本

1.1.7

### 描述一下此特性

- `halo-theme-joe2.0` 的轮播图的缩放方式是等比缩放，而本主题会裁切，希望可以添加一个按钮选择
- `halo-theme-joe2.0` 的轮播图可以不指定标题和跳转链接，可以纯粹的放一张图片展示，希望可以抄过来

**Comment by jiewenhuang** [comment]
移植的时候，所有样式应该是不变的，具体剪裁是怎么样的？

**Comment by jiewenhuang** [comment]
<img width="359" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/c9f0cca3-73ce-4bd4-a449-56d3ee088feb">
  

目前的缩放方式是cover
