### ISSUE TITLE
深色模式，文章中文字颜色太深，看不清

### ISSUE THREAD

**Issue by mutouloves** [jiewenhuang/halo-theme-joe3.0#197]
### 是什么版本出现了此问题？

1.1.7

### 发生了什么？

文章中文字颜色太深，看不清
![1](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/82205731/9b5412c1-a45d-4694-9639-805ff21fe782)

**Comment by jiewenhuang** [comment]
<img width="855" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/a5ffcd5e-bc75-43a8-92fa-2a220d0a523b">
   
具体？

**Comment by mutouloves** [comment]
找到原因了，不是主题的问题，是 Vditor编辑器 插件更新后引起的，感谢大神回复
