### ISSUE TITLE
友链页怎么加路由啊，还有菜单图标咋个更改呢，求指点😫

### ISSUE THREAD

**Issue by Poison02** [jiewenhuang/halo-theme-joe3.0#20]
友链我没找到自定义页面有诶，怎么加路由呢？
以及菜单的图标在哪里修改呢？在`iconfont`复制的是什么格式呀？

**Comment by jiewenhuang** [comment]
友链是/links，安装插件后访问即可，图标看这个https://www.jiewen.run/archives/joe3use

**Comment by Poison02** [comment]
> 友链是/links，安装插件后访问即可，图标看这个https://www.jiewen.run/archives/joe3use

好的好的，现在看到了，打扰了！非常感谢！
