### ISSUE TITLE
启用 Waline 系统无法进行评论

### ISSUE THREAD

**Issue by qianmoQ** [jiewenhuang/halo-theme-joe3.0#200]
### 是什么版本出现了此问题？

1.1.7

### 在线站点地址

https://devlive.org

### 发生了什么？

启用 Waline 系统无法进行评论出现 
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/20521442/b7729355-5443-4b4b-b465-5c448baedbcb)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/20521442/2d6da064-1d8e-4b8c-bf62-c36ee86a1331)
直接访问部署系统返回的地址可以准确评论
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/20521442/ba25b8e6-219a-4e68-bd21-beb2a26236da)

**Comment by jiewenhuang** [comment]
尝试填写一下我的waline评论看看。https://waline-comment-jiewen.lanyuku.com 如果换我的这个没有问题，可能是你那边部署的问题

**Comment by jiewenhuang** [comment]
这个似乎是你的vercel应用没有开放权限。  
<img width="1466" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/38767855-88dd-4ca6-ab26-1af72e3fa2d5">

**Comment by jiewenhuang** [comment]
不清楚，没遇到过
