### ISSUE TITLE
更新包有传错吗？

### ISSUE THREAD

**Issue by duanluan** [jiewenhuang/halo-theme-joe3.0#204]
### 是什么版本出现了此问题？

1.1.8

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/14957667/ab78c995-32f1-419c-a84a-d00a3a1fda23)

**Comment by jiewenhuang** [comment]
这是action自动打包的，内容应该没错，名字不知道为什么出问题了
