### ISSUE TITLE
文章详情页用户信息，文章目录，相关文章三个区域重叠

### ISSUE THREAD

**Issue by ldwcool** [jiewenhuang/halo-theme-joe3.0#206]
### 是什么版本出现了此问题？

1.1.7

### 在线站点地址

https://ldw.cool/archives/1700445951692

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/139094465/95bbb3aa-a6e4-4b0c-8fbc-38381f963932)

**Comment by jiewenhuang** [comment]
插件列表，看看有没有启用toc插件，有的话，关掉看看

**Comment by ldwcool** [comment]
解决了，果然是toc插件的问题，关掉就好了。
