### ISSUE TITLE
关于博主信息昵称旁边的“LV 1”图标的问题

### ISSUE THREAD

**Issue by Raistlind** [jiewenhuang/halo-theme-joe3.0#207]
### 是什么版本出现了此问题？

1.1.8

### 发生了什么？

1、博主信息昵称旁边的“LV1”字样无法关闭，系统目前也没有会员级别的功能，最好能给出是否显示的配置选项。
2、“LV 1"上面绑定的链接无法配置，默认链接自动指向halo默认端口号，但那个端口地址通常外部是无法访问的，希望能提供配置地址功能。
<img width="330" alt="PixPin_2024-01-31_15-47-22" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/7170828/d7d12a91-66e2-4a97-be5b-7a0bb40a8b1d">

**Comment by jiewenhuang** [comment]
这里指向的是外部访问地址，按照Halo文档的说法，这个地址是实际访问地址是什么就填什么，比如你访问地址是https://example.com ,就填https://example.com，不存在说什么端口号问题。

**Comment by Raistlind** [comment]
实际上是碰到了端口号的问题。根据halo文档在1panel下的安装过程，在安装halo时，会指定端口为8080，但是在建立网站后，在openresty将通过80转发到8080。同时，设置了网站的证书后，8080就不能访问了。所以默认生成的地址xxx.cn:8080就出现问题了。请看看有没有什么办法解决，谢谢~

**Comment by Raistlind** [comment]
主要是实际组网时，会openresty会把http都转为https，而halo本身默认的地址，只支持http。所有的https请求必须通过openresty的80端口访问。所以这里就出现了冲突，要么网站允许http直接访问，要么就不要用域名+halo端口访问，而是使用openresty的监听端口，即80端口。

**Comment by jiewenhuang** [comment]
虽然，没看懂，但，这似乎是1panel的问题？

**Comment by Raistlind** [comment]
找到解决的办法了，在1panel里，把halo应用配置参数的链接地址，直接改为最终的地址就可以了。

**Comment by majinshan** [comment]
没看明白楼主是怎么解决的，我也想关闭等级图标的，是用docker安装的。
能通过配置关闭吗？
