### ISSUE TITLE
文章内打赏图标缺失

### ISSUE THREAD

**Issue by XiaoFuOS** [jiewenhuang/halo-theme-joe3.0#210]
### 是什么版本出现了此问题？

 1.1.8

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/103229747/58c9a268-d34d-475d-91c6-f9803676b41a)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/103229747/301fa018-4c9b-4c30-a954-bfd0b10c7f77)
新版有个名为joe-font joe-icon-shang的css名丢失了，导致不显示打赏图标，不知道是不是我的问题

**Comment by jiewenhuang** [comment]
这个似乎没有做做过改动,可以检查下是不是自己加的图标冲突了

**Comment by Einstein-schrodinger** [comment]
> 这个似乎没有做做过改动,可以检查下是不是自己加的图标冲突了

我的也不显示

**Comment by XiaoFuOS** [comment]
> 这个似乎没有做做过改动,可以检查下是不是自己加的图标冲突了

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/103229747/ee61b197-c40c-481a-a25b-c20e5f4eddc6)
放到全屏的时候，侧面图标是有的，但是缩小了，在文章内不显示图标
