### ISSUE TITLE
文章页显示KaTeX数学公式问题

### ISSUE THREAD

**Issue by haonanaJava** [jiewenhuang/halo-theme-joe3.0#215]
### 是什么版本出现了此问题？

1.1.8

### 在线站点地址

http://www.heyutang.icu/

### 发生了什么？

我安装了KateX插件，使用了Theme-Joe3主题。文章页对KaTeX数学公式的渲染有点问题，但是在编辑器中可以正常显示。
### 这是编辑器页的截图
![Snipaste_2024-02-14_13-41-41](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/57832817/7d203cad-a113-46da-b0e2-004103fdcf92)
### 这是文章页的截图
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/57832817/c5937941-a981-4b48-8e33-6a725aabb1ae)

**Comment by jiewenhuang** [comment]
用了tool插件的，会有冲突
