### ISSUE TITLE
升级到1.1.9后图库加载不出来

### ISSUE THREAD

**Issue by liuhuongtao** [jiewenhuang/halo-theme-joe3.0#220]
### 是什么版本出现了此问题？

1.1.9

### 发生了什么？

切换回halo默认主题，图库可以正常加载

**Comment by jiewenhuang** [comment]
信息不够，判断不了

**Comment by suxiaolinya** [comment]
![101](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/105998937/c6192f01-ab41-4ebb-b933-43b3683227e8)
我也是图库加载不出来，这是报错

**Comment by suxiaolinya** [comment]
Failed to load resource: the server responded with a status of 404 ()      apis/api.plugin.halo.run/v1alpha1/plugins/PluginPhotos/photos:1 
我也是这个问题，上面是报错

**Comment by suxiaolinya** [comment]
在线网址:www.suxiaolin.top halo版本:2.12.3  图库插件版本:1.3.0

**Comment by suxiaolinya** [comment]
> > 在线网址:www.suxiaolin.top halo版本:2.12.3 图库插件版本:1.3.0
> 
> 应该是图库更改api信息，尝试退回低版本看看

图库版本:1.2.0 正常可用

**Comment by liuhuongtao** [comment]
在图库插件最新版本 1.3.0 中，修改了一个 BUG，该 BUG 会导致任何用户都可以访问你的图库。

Joe 主题应该是在代码中利用了这个 BUG 来展示当前用户的所有图库。
如果想解决问题，可以临时将图库插件回退到 1.2.0。不过这始终是一个不安全的做法，建议向主题仓库提一个 issue 用来解决这个问题，主题端建议使用 finder api 来调用图库。 






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年2月26日 19:51 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [jiewenhuang/halo-theme-joe3.0] 升级到1.1.9后图库加载不出来 (Issue #220) |

在线网址:www.suxiaolin.top halo版本:2.12.3 图库插件版本:1.3.0

应该是图库更改api信息，尝试退回低版本看看

**Comment by Zakkoree** [comment]
图库版本1.3.0  代码变更
 -     "/apis/api.plugin.halo.run/v1alpha1/plugins/PluginPhotos/photogroups"
 +     "/apis/console.api.photo.halo.run/v1alpha1/photogroups"

主题版本1.1.9
我更改了 photos.js和photos.main.js中的API， 但不会生效
调用的还是老的API，这是因为啥呢

> > 在线网址:www.suxiaolin.top halo版本:2.12.3 图库插件版本:1.3.0
> 
> 应该是图库更改api信息，尝试退回低版本看看

**Comment by jiewenhuang** [comment]
> 图库版本1.3.0 代码变更
> 
> * ```
>   "/apis/api.plugin.halo.run/v1alpha1/plugins/PluginPhotos/photogroups"
>   ```
> 
> * ```
>   "/apis/console.api.photo.halo.run/v1alpha1/photogroups"
>   ```
> 
> 主题版本1.1.9 我更改了 photos.js和photos.main.js中的API， 但不会生效 调用的还是老的API，这是因为啥呢
> 
> > > 在线网址:www.suxiaolin.top halo版本:2.12.3 图库插件版本:1.3.0
> > 
> > 
> > 应该是图库更改api信息，尝试退回低版本看看

1.3之后的接口需要鉴权
