### ISSUE TITLE
文章详情页侧边栏的点赞和评论不显示具体数目

### ISSUE THREAD

**Issue by stars-one** [jiewenhuang/halo-theme-joe3.0#222]
### 是什么版本出现了此问题？

1.1.4

### 在线站点地址

https://stars-one.site

### 发生了什么？

如下图所示

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/31400169/5f35d23d-690c-4f70-8cff-45187b56ec6d)

目前还没测试新版1.1.9,晚上再测试看看

**Comment by stars-one** [comment]
已测试,1.1.9版本也有此问题

**Comment by stars-one** [comment]
> 因为这个压根没写，宝贝

移植不到位啊 😂

**Comment by stars-one** [comment]
侧边的那个代码是在哪个文件,我尝试下能不能改下?找了半天都没找到在哪

**Comment by jiewenhuang** [comment]
<img width="1148" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/f0d639a3-17f9-4acc-a685-7572bcef7483">

**Comment by stars-one** [comment]
1.2.1版本,测试还是不行呢...
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/31400169/c5018ca1-81b7-41bc-bc8c-80cebf5723c7)
