### ISSUE TITLE
私有文章支持目录

### ISSUE THREAD

**Issue by sherlocky** [jiewenhuang/halo-theme-joe3.0#232]
### 你当前使用的版本

 1.2.2

### 描述一下此特性

当前私有的文章不展示文章目录，是否有必要支持下~

**Comment by jiewenhuang** [comment]
<img width="1422" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/ddccbc6a-37c2-40c4-a983-e4d4088daf31">  

？

**Comment by sherlocky** [comment]
我又测试了下，有的私有博文可以，不是私有文章的问题，换了个主题就可以显示了
<img width="966" alt="123-00" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/8652013/609bc886-8dd8-4a47-b155-cd4ed4a07f68">
<img width="1008" alt="123-01" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/8652013/fe238c64-efca-4bcb-ab14-aab76511cdfc">
<img width="1124" alt="123-02" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/8652013/6f7f71ca-8d78-47e9-ba7a-a478518d0279">

是不是这篇博文里有特殊字符什么之类导致的

**Comment by sherlocky** [comment]
我把文章的markdown内容复制出来，新建一个文章就正常了。。神奇
