### ISSUE TITLE
这个下划线不会动

### ISSUE THREAD

**Issue by JUNQINGV587** [jiewenhuang/halo-theme-joe3.0#233]
### 是什么版本出现了此问题？

all

### 发生了什么？

这个下划线不会动，一直在这里：
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/22016714/c8492cda-d81c-4fef-935b-4cfbcde29b8c)

### 相关日志输出

```shell
这个下划线不会动
```

### 附加信息

这个下划线不会动

**Comment by jiewenhuang** [comment]
只有演示地址有，应该是地址的问题

**Comment by JUNQINGV587** [comment]
> 只有演示地址有，应该是地址的问题

我本地新部署的也有

**Comment by jiewenhuang** [comment]
<img width="1475" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/81b8f3dc-6f25-4b9b-a54c-c6c85f85a58c">
<img width="1475" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/a262a066-750d-42b4-add6-0bd36d8551c2">
<img width="1430" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/36e86440-1544-4d93-bb4d-44d3b29695c8">

**Comment by JUNQINGV587** [comment]
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/22016714/82e073db-af86-4fff-952d-96abd67d9ae2)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/22016714/ed83b341-d488-4c54-8288-c7664e56d5fb)

**Comment by jiewenhuang** [comment]
不知，没遇到过，看了一眼别人的，也没看见  
<img width="1472" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/c51ad23b-d335-423e-8521-a680dfd89979">

**Comment by jiewenhuang** [comment]
这个应该是根据地址栏地址判断的，尝试换一下路径
