### ISSUE TITLE
xml文件中如果有注释， 就会被转义

### ISSUE THREAD

**Issue by jiangqiang1996** [jiewenhuang/halo-theme-joe3.0#234]
### 是什么版本出现了此问题？

最新

### 在线站点地址

https://www.jiangqiang.top/archives/shi-yong-sentinelshi-xian-fu-wu-rong-duan-yu-jiang-ji

### 发生了什么？

xml格式的代码中如果存在注释，就会被转义成实体符号
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/44720422/99126a00-7a3a-4025-a652-b0fc99b8037c)

**Comment by jiewenhuang** [comment]
这因该是插件问题，关掉就好了
