### ISSUE TITLE
似乎没有对halo默认的评论区做暗色适配

### ISSUE THREAD

**Issue by jcwang99** [jiewenhuang/halo-theme-joe3.0#235]
### 是什么版本出现了此问题？

最新版本

### 在线站点地址

https://991198.xyz

### 发生了什么？

在暗色模式下，halo默认评论区的文字没有适配，类似下面这样
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/44741516/c366b689-6e15-42f8-a790-370a8ca4b9e0)

**Comment by jiewenhuang** [comment]
7093967c5e8017f77d9523dbc582011778014188 
还没合并发版
