### ISSUE TITLE
三级菜单创建不出来 最多二级

### ISSUE THREAD

**Issue by Kimser** [jiewenhuang/halo-theme-joe3.0#238]
### 是什么版本出现了此问题？

2.13

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/54876002/1b2141f9-0395-4728-aebc-6777bc4369ca)
三级菜单创建了 主站没渲染 最多二级

**Comment by jiewenhuang** [comment]
设计就是如此，三级很丑

**Comment by qiushaocloud** [comment]
@Kimser 我这边也是有三级菜单的需求，我自己实现了代码，也申请了合并

我博客应用的主题项目：https://github.com/qiushaocloud/halo-theme-joe3.0-qiu

fork 过去后修改的项目：https://github.com/qiushaocloud/halo-theme-joe3.0

这是应用修改后的预览地址：https://www.qiushaocloud.top/2024/05/05/halo2x-joe30-zhu-ti-qiu-shao-xiu-gai-ban
