### ISSUE TITLE
搜索按钮后面藏了个小彩蛋？

### ISSUE THREAD

**Issue by Litbay** [jiewenhuang/halo-theme-joe3.0#24]
Joe3.0@1.0.4版本，在搜索按钮下方有一个小黑点
![屏幕截图 2023-08-17 155948](https://img.gugu.ovh/i/2023/08/17/qi0ejw.webp)
一开始我以为是我的屏幕脏了，试着擦了下发现擦不掉，检查了下是真的有东西显示出来的，用浏览器开发者选项发现，删除button标签后显示一个像33的小人物
![屏幕截图 2023-08-17 160155](https://img.gugu.ovh/i/2023/08/17/qi0hd1.webp)
原因是button标签的下面有这么一行代码
![屏幕截图 2023-08-17 160132](https://img.gugu.ovh/i/2023/08/17/qi0h90.webp)
这个小人物貌似没啥作用，不确定是不是大佬们没删干净这个span标签还是故意藏的，来提个issue看看
故意藏的话麻烦大佬们塞进去一点，不要露出来

**Comment by poiiwe** [comment]
竟然添加了bug标签，原来是bug嘛-_-？
