### ISSUE TITLE
关于：主题相关 > 链接跳转行为

### ISSUE THREAD

**Issue by tom-kst** [jiewenhuang/halo-theme-joe3.0#242]
### 你当前使用的版本

1.2.2

### 描述一下此特性

**JOE3主题**确实很强，但是有些地方不尽如人意，例如：链接跳转行为（全局-内容区域）中，选用“默认”、“新标签”都会在新标签中打开文章，然而如果设置当前页打开则所有文章内的外链也会被全局（文章中是设置了新标签打开的）。
我另一个blog使用Typecho，也是用**JOE主题**，就是手动去掉大部分的`target="_blank"`标签，能达到当前页打开文章，文内外链则是新标签这个效果。然后Halo我也想照葫芦画瓢，但却依然没有作用（修改完有重启Halo Docker）。
大佬能不能稍稍修改一下这个跳转代码，把所有站内文章、内链改为当前页，外链才开新标签？

**Comment by jiewenhuang** [comment]
那这样，全局跳转设置的意义在哪里呢，还有，就是应该如何判断哪些是站内链接，哪些是站外链接？这种更改，我觉得更像是私人化的习惯，你可以自己fork仓库后，自行按照需要更改，要注意的是主题只引用min，下面压缩后的js，但是未提供自动化的构建，你需要自行配置。

**Comment by tom-kst** [comment]
那这样跳转就是：默认=新标签（这两个选项几乎没有区别），然后另一个选项就是当前页。
而我个人理解的是：应该判断`<a href="" target="_blank" rel="">`整个条件，而不是单纯判断`<a href="">`

**Comment by jiewenhuang** [comment]
默认是只处理文章内容为打开新标签，其他页面保持原有打开方式，从人性化设置的角度来说，是没有问题的，因为你不可能，在看文章的时候里面有引用其他内容，打开却是内部跳转，还需要返回才能查看文章。至于你说的_blank问题，如果只判断_blank .那_parent, _top这些事件应该是怎么处理的呢。

**Comment by tom-kst** [comment]
> 默认是只处理文章内容为打开新标签，其他页面保持原有打开方式，从人性化设置的角度来说，是没有问题的，因为你不可能，在看文章的时候里面有引用其他内容，打开却是内部跳转，还需要返回才能查看文章。至于你说的_blank问题，如果只判断_blank .那_parent, _top这些事件应该是怎么处理的呢。

但是默认跳转在主页、文章列表时，点击文章也是跳转新标签呢，也就跟新标签跳转一样了……所以想问问大佬

**Comment by tom-kst** [comment]
大佬，我没有要挑剔的意思，请不要见怪。只是可能我描述的不是很清楚吧。。。
我重新组织一下目前在使用Joe3.0的情况：
**默认：**主页、文章列表、归档页点击文章标题 >> 主题目前是`新标签`打开（_而我所理解的**默认**应该是从父页打开，不跳转新页_）；
**当前页：**所有链接均为从父页打开，不跳转新页面；
**新标签：**所有链接均为新页打开。

**Comment by jiewenhuang** [comment]
> 大佬，我没有要挑剔的意思，请不要见怪。只是可能我描述的不是很清楚吧。。。 我重新组织一下目前在使用Joe3.0的情况： **默认：** 主页、文章列表、归档页点击文章标题 >> 主题目前是`新标签`打开（_而我所理解的`默认`应该是从父页打开，不跳转新页，而文中的链接则按在编辑时所设定的行为方式来执行_）； **当前页：** 所有链接均为从父页打开，不跳转新页面； **新标签：** 所有链接均为新页打开。

这个保持的Joe2的行为，写死的，也是众口难调的问题，可以把对应页面的跳转改一下，应该没有多少页
