### ISSUE TITLE
自定义favicon 不生效

### ISSUE THREAD

**Issue by VanLiuZhi** [jiewenhuang/halo-theme-joe3.0#243]
### 是什么版本出现了此问题？

1.2.2

### 发生了什么？

看控制台资源已经加载了，但是配置不生效，无任何报错

主题：1.2.2
halo：2.14.0

<img width="571" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/22883555/dd3e5578-701a-4028-9875-f6883bad709c">

<img width="1280" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/22883555/767891f9-7c8e-41df-8c32-5657124633fc">

**Comment by jiewenhuang** [comment]
在Halo 的设置那里加看看，可能被覆盖了

**Comment by VanLiuZhi** [comment]
> 在Halo 的设置那里加看看，可能被覆盖了

确实是这样，感谢，问题已经解决了
