### ISSUE TITLE
文章页显示KaTeX数学公式问题

### ISSUE THREAD

**Issue by gcindy** [jiewenhuang/halo-theme-joe3.0#249]
### 是什么版本出现了此问题？

 1.2.2

### 在线站点地址

https://blog.gongyibai.cn/

### 发生了什么？

在用Halo默认编辑器时没问题能正常展示，用StackEdit / ByteMD时候编辑能展示公式，文章页展示不了。
地址：https://blog.gongyibai.cn/archives/769af937-6dee-4ffe-9efe-576686a6c74a 、https://blog.gongyibai.cn/archives/cheng-ben-lei-ji-suan-ti

<img width="1274" alt="3" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/37326714/aac4d8c3-318d-4cda-a2db-a20e7fd08956">
<img width="1281" alt="1" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/37326714/49130e2f-680d-463f-9fa0-525b03040ea3">
<img width="1302" alt="2" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/37326714/267b80b9-f59e-41d5-b596-d094c4f34261">
![IMG_3180](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/37326714/df9f7c49-294a-4aad-b638-d77ddadac410)
<img width="1016" alt="stackEdit" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/37326714/e2cc0745-f4e6-440a-b5ba-13b597d58896">

**Comment by gcindy** [comment]
<img width="976" alt="默认编辑器" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/37326714/f30d9330-4deb-49c4-b40b-4d75dc6e7e03">

**Comment by jiewenhuang** [comment]
这个应该是哥哥编辑器的语法显示问题，做不到完全兼容喔
