### ISSUE TITLE
菜单栏的图标不会使用

### ISSUE THREAD

**Issue by qiushaocloud** [jiewenhuang/halo-theme-joe3.0#255]
### 是什么版本出现了此问题？

最新

### 发生了什么？

菜单栏的图标请使用[iconfont](https://www.iconfont.cn/)的图标，需要填入Font Family 和图标代码例如：jiewen joe-icon-tupian

请问如何才能得到图标代码，希望提供相关操作图

**Comment by jiewenhuang** [comment]
https://www.jiewen.run/archives/joe3use

**Comment by qiushaocloud** [comment]
谢谢
