### ISSUE TITLE
文章目录会随页面滑动而变换位置

### ISSUE THREAD

**Issue by Lyn4ever29** [jiewenhuang/halo-theme-joe3.0#26]
### 是什么版本出现了此问题？

1.0.7

### 发生了什么？

文章目录会随页面滑动而变换位置
正常是这样
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/25952589/5d0ad8b6-3a8e-4218-9ef0-3f412957b7b2)

页面滑动了是这样
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/25952589/c4b5e44f-f8bd-4d14-918b-3c1a3017fd93)

**Comment by NSKW22** [comment]
为啥我的不显示目录啊
