### ISSUE TITLE
文章无法打赏

### ISSUE THREAD

**Issue by ACZSHOP** [jiewenhuang/halo-theme-joe3.0#27]
### 是什么版本出现了此问题？

1.0.5

### 在线站点地址

aczshop.top

### 发生了什么？

在后台已经设置好打赏功能了，实际上在文章里面并没有显示打赏按钮

![1](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/142337549/b5470e77-6763-452f-a8c5-60e111ac356d)
![2](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/142337549/9d1bc6a9-fbac-420e-8dc0-39a5efc01a15)

**Comment by jiewenhuang** [comment]
文章设置找到打赏重新选择发布一下，那里做过更改

**Comment by ACZSHOP** [comment]
> 还是不显示呢

**Comment by ACZSHOP** [comment]
还是不显示呢

**Comment by ACZSHOP** [comment]
> 还是不显示呢，我重新开关和换了图片

**Comment by jiewenhuang** [comment]
有joe2.0的交流群吗？有的话直接艾特下我，我看看是怎么个回事

**Comment by ACZSHOP** [comment]
> 解决了，重新发布了文章

**Comment by ACZSHOP** [comment]
> 解决了，重新发布了文章
