### ISSUE TITLE
Maybe is a bug: 表格渲染不完整

### ISSUE THREAD

**Issue by QingFeng-awa** [jiewenhuang/halo-theme-joe3.0#270]
### 是什么版本出现了此问题？

1.2.2

### 在线站点地址

https://www.xtreme.net.cn

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/151742581/bfec77f5-9010-4867-8e51-6609dcf4e48e)
如图,表格的部分竖线没有被渲染,并且这看上去是刻意为之的。
我希望在新版本移除这个特性或允许在设置中选择是否开启。

#### 系统信息
- 外部访问地址: https://www.xtreme.net.cn
- 出现问题的URL: https://www.xtreme.net.cn/tutorialTONEX
- 启动时间: 2024-05-10 20:36
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:22
- Git Commit: fba7d0a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-105-generic
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Trailing Slash](https://github.com/halo-sigs/plugin-trailing-slash)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

> _另外,Joe3已经有较长时间没有更新了,issue也越来越多,能推送新版本了吗?_

**Comment by freedomgod** [comment]
我也遇到了表格渲染的问题，但不清楚是哪里的问题。在Halo控制台创建文章，使用的是Vditor Markdown编辑器，可以正常显示表格，但发布后表格就渲染不了。详细可以查看：https://whfree.top/archives/markdown-usage-guide
![PixPin_2024-05-18_14-14-54](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/59652488/afd60b23-a417-4e5f-b7a3-d78e902d431a)
![PixPin_2024-05-18_14-14-30](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/59652488/0365f995-c292-4b41-a2ae-4fd5f8d35dbe)

**Comment by QingFeng-awa** [comment]
> 我也遇到了表格渲染的问题，但不清楚是哪里的问题。在Halo控制台创建文章，使用的是Vditor Markdown编辑器，可以正常显示表格，但发布后表格就渲染不了。详细可以查看：https://whfree.top/archives/markdown-usage-guide ![PixPin_2024-05-18_14-14-54](https://private-user-images.githubusercontent.com/59652488/331770712-afd60b23-a417-4e5f-b7a3-d78e902d431a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQwNTksIm5iZiI6MTcxNjM3Mzc1OSwicGF0aCI6Ii81OTY1MjQ4OC8zMzE3NzA3MTItYWZkNjBiMjMtYTQxNy00ZTVmLWI3YTMtZDc4ZTkwMmQ0MzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOGZiY2M1MTFlMTEzMzgzZGFjODQzZDEzM2MwMTJiZmNkNmQyNWYxYTY4ZjliN2MyMjVlNjEzZThhOWNmOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U9KKqxfJqfhIy8Vgfi-RF9ryyK-F-Tqcw3Wc_RiBRuY) ![PixPin_2024-05-18_14-14-30](https://private-user-images.githubusercontent.com/59652488/331770714-0365f995-c292-4b41-a2ae-4fd5f8d35dbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQwNTksIm5iZiI6MTcxNjM3Mzc1OSwicGF0aCI6Ii81OTY1MjQ4OC8zMzE3NzA3MTQtMDM2NWY5OTUtYzI5Mi00YjQxLWEyYWUtNGZkNWY4ZDM1ZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZGVhN2M4ZjgzN2U0NzRjNGMwNjQzMWQ4MDExZTM2ZWI4MTYzNTA1MTUyYjQyMmM2MGU0YTA5YTU5YTU3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uA7O41OJ5_5f9ZJsFPlqxbpW7oXZ4ORTjJxrrd0xsQ0)

这个是因为Vditor编辑器不支持这种渲染方式,你需要`Ctrl` + `M`创建表格或点击按钮创建表格。

**Comment by freedomgod** [comment]
> > 我也遇到了表格渲染的问题，但不清楚是哪里的问题。在Halo控制台创建文章，使用的是Vditor Markdown编辑器，可以正常显示表格，但发布后表格就渲染不了。详细可以查看：https://whfree.top/archives/markdown-usage-guide ![PixPin_2024-05-18_14-14-54](https://private-user-images.githubusercontent.com/59652488/331770712-afd60b23-a417-4e5f-b7a3-d78e902d431a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQwNTksIm5iZiI6MTcxNjM3Mzc1OSwicGF0aCI6Ii81OTY1MjQ4OC8zMzE3NzA3MTItYWZkNjBiMjMtYTQxNy00ZTVmLWI3YTMtZDc4ZTkwMmQ0MzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOGZiY2M1MTFlMTEzMzgzZGFjODQzZDEzM2MwMTJiZmNkNmQyNWYxYTY4ZjliN2MyMjVlNjEzZThhOWNmOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U9KKqxfJqfhIy8Vgfi-RF9ryyK-F-Tqcw3Wc_RiBRuY) ![PixPin_2024-05-18_14-14-30](https://private-user-images.githubusercontent.com/59652488/331770714-0365f995-c292-4b41-a2ae-4fd5f8d35dbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQwNTksIm5iZiI6MTcxNjM3Mzc1OSwicGF0aCI6Ii81OTY1MjQ4OC8zMzE3NzA3MTQtMDM2NWY5OTUtYzI5Mi00YjQxLWEyYWUtNGZkNWY4ZDM1ZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZGVhN2M4ZjgzN2U0NzRjNGMwNjQzMWQ4MDExZTM2ZWI4MTYzNTA1MTUyYjQyMmM2MGU0YTA5YTU5YTU3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uA7O41OJ5_5f9ZJsFPlqxbpW7oXZ4ORTjJxrrd0xsQ0)
> 
> 这个是因为Vditor编辑器不支持这种渲染方式,你需要`Ctrl` + `M`创建表格或点击按钮创建表格。

不是吧，我上面的截图中使用Vditor编辑器，右边表格不是渲染成功了吗，这说明肯定是支持的。只是预览或者发布后就不对了。我不太清楚Halo在渲染页面的时候是不是就是用对应编辑器插件来渲染的？如果不是的话，那不管用什么Markdown编辑器都会被限制，因为编辑器支持的扩展语法不能在最终展示的页面中显示。

**Comment by QingFeng-awa** [comment]
> 不是吧，我上面的截图中使用Vditor编辑器，右边表格不是渲染成功了吗，这说明肯定是支持的。只是预览或者发布后就不对了。我不太清楚Halo在渲染页面的时候是不是就是用对应编辑器插件来渲染的？如果不是的话，那不管用什么Markdown编辑器都会被限制，因为编辑器支持的扩展语法不能在最终展示的页面中显示。

不好意思,这是我的错误,Vditor编辑器支持此种表格,但你的表格不能渲染是因为你的表格写错了……
请将`| ———————————————————— | ———————————————————— |`替换为`| --- | --- |`。

**Comment by QingFeng-awa** [comment]
我现在准备将站点的主题换为Hao / iEmo,因此这个issue没必要继续open了。
