### ISSUE TITLE
点赞功能失效和点赞功能样式丢失

### ISSUE THREAD

**Issue by xgr5202** [jiewenhuang/halo-theme-joe3.0#286]
### 是什么版本出现了此问题？

halo2.15.2以上的版本均会出现这个问题

### 在线站点地址

https://ssl.xgrsir.com/archives/hello-halo

### 发生了什么？

这是有问题的样式显示
![有问题](https://github.com/user-attachments/assets/446df466-da02-4662-bd05-cfc82c0ec203)
这是没问题的样式显示
![没问题](https://github.com/user-attachments/assets/80766ecf-71e3-4194-b1ab-9998e53aa14a)
这是浏览器显示的错误信息
![错误信息](https://github.com/user-attachments/assets/6e73db3b-41e5-4f4d-b2e1-3fc78058dc8d)

**Comment by langoyb** [comment]
#276 参考这个，我这边也有这个问题。目前是回退2.15.2使用。
可以考虑这两个方法试试：
1、删除\halo-theme-Joe3-1.2.2\templates\assets\js\min\下所有gz包重启容器
2、修改nginx反代地址为域名或者IP试试
不敢保证有效，反正就是折腾。实在不行就重装2.15.2，然后就是静候作者修复。

**Comment by xgr5202** [comment]
> #276参考这个，我这边也有这个问题。目前是回退2.15.2使用。 可以考虑这两个方法试试： 1、删除\halo-theme-Joe3-1.2.2\templates\assets\js\min\下所有gz包重启容器 2、修改nginx反代地址为域名或者IP试试 不敢保证有效，反正就是折腾。实在不行就重装2.15.2，然后就是静候作者修复。

按照您说的第一个办法，成功显示了！
![xianshi](https://github.com/user-attachments/assets/5722b4c7-2d46-498b-941e-e47e9d12fee3)
