### ISSUE TITLE
在导航栏中添加登录入口及登录状态显示

### ISSUE THREAD

**Issue by Litbay** [jiewenhuang/halo-theme-joe3.0#29]
### 你当前使用的版本

1.0.5

### 描述一下此特性

是否考虑在导航栏添加用户登录的入口？以及登录状态下显示小头像，方便进入后台。目前进入后台只能在地址栏手打/console路由，挺不方便的

**Comment by ACZSHOP** [comment]
@jiewenhuang 这个功能什么时候可以加上，等了很久了

**Comment by jiewenhuang** [comment]
pr welcome 这个功能我不会

**Comment by ACZSHOP** [comment]
> 公关欢迎 这个功能我不会

试试看在菜单键添加登录和注册的链接能不能解决https://bbs.halo.run/d/4271-%E6%80%8E%E4%B9%88%E6%8A%8A%E6%B3%A8%E5%86%8C%E7%99%BB%E9%99%86%E5%85%A5%E5%8F%A3%E8%AE%BE%E5%88%B0%E4%B8%BB%E8%8F%9C%E5%8D%95/4
