### ISSUE TITLE
代码注入自定义页脚BUG，无法自定义页脚信息，去掉自定义信息后页面不更新

### ISSUE THREAD

**Issue by Dangks** [jiewenhuang/halo-theme-joe3.0#292]
### 是什么版本出现了此问题？

2.17.1

### 在线站点地址

https://www.dangks.online/

### 发生了什么？

使用设置中的代码注入自定义页脚信息（增加萌备），但是首页和文章页面不生效，像“相册”、“瞬间”这种插件提供的页面可以生效。但是去除注入代码后相关页面的注入信息仍然还在，现在就是卡住，不能注入新的，之前注入的去掉也还显示。

**Comment by jiewenhuang** [comment]
具体配置可以看下吗？如果是注入代码，建议使用halo自带的

**Comment by Dangks** [comment]
> 具体配置可以看下吗？如果是注入代码，建议使用halo自带的

刚刚更新了主题1.3版本，注入信息取消后仍然显示在其他页面的BUG没了，但是现在还是无法注入页脚信息
![Prtscr_2024-07-17_22-21-53](https://github.com/user-attachments/assets/01006532-ad39-495a-9276-b1246552c266)

**Comment by ruibaby** [comment]
> 刚刚更新了主题1.3版本，注入信息取消后仍然显示在其他页面的BUG没了，但是现在还是无法注入页脚信息

这个我看了代码，没有添加 <halo:footer /> 标签，后面的版本会加上。

**Comment by acanyo** [comment]
> <halo:footer />

什么时候能修复

**Comment by acanyo** [comment]
> > 刚刚更新了主题1.3版本，注入信息取消后仍然显示在其他页面的BUG没了，但是现在还是无法注入页脚信息
> 
> 这个我看了代码，没有添加 <halo:footer /> 标签，后面的版本会加上。

什么时候能修复
