### ISSUE TITLE
1.3.0 更新后友链评论区提示 Comment widget attributes 'name' is required but missing found.

### ISSUE THREAD

**Issue by duanluan** [jiewenhuang/halo-theme-joe3.0#303]
### 是什么版本出现了此问题？

1.3.0

### 在线站点地址

https://blog.zhjh.top/links

### 发生了什么？

友链评论区提示 Comment widget attributes 'name' is required but missing found.

**Comment by jiewenhuang** [comment]
更新评论插件

**Comment by duanluan** [comment]
> 更新评论插件

评论插件更新到了 2.4.0，docker 重启了 Halo，还是报这个错

**Comment by Sakura-LF** [comment]
我也有这个问题

**Comment by ruibaby** [comment]
需要确保链接插件是 1.4.0 版本：https://github.com/halo-sigs/plugin-links/releases/tag/v1.4.0

**Comment by Sakura-LF** [comment]
重启了一下就解决了😂

**Comment by duanluan** [comment]
> 确保链接插件是 1.4.0 版本

管理后台 - 插件 里不会提示更新，手动升级一下确实好了。
