### ISSUE TITLE
站点运行时间显示不正常

### ISSUE THREAD

**Issue by codesensi** [jiewenhuang/halo-theme-joe3.0#31]
### 是什么版本出现了此问题？

1.0.5

### 在线站点地址

https://halo.codesensi.cn:1443/

### 发生了什么？

首页、分类、标签页面的站点运行时间为00 天 00 时 00 分 00 秒，文章详情页正常显示

### 附加信息

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/66196408/cd534d76-8f23-4621-abec-0b2104f56083)

**Comment by dengchuanfu** [comment]
> ### 是什么版本出现了此问题？
> 1.0.5
> 
> ### 在线站点地址
> https://halo.codesensi.cn:1443/
> 
> ### 发生了什么？
> 首页、分类、标签页面的站点运行时间为00 天 00 时 00 分 00 秒，文章详情页正常显示
> 
> ### 相关日志输出
> _No response_
> 
> ### 附加信息
> ![image](https://user-images.githubusercontent.com/66196408/261845560-cd534d76-8f23-4621-abec-0b2104f56083.png)

我的也是
