### ISSUE TITLE
博客地址与实际地址不匹配

### ISSUE THREAD

**Issue by Rising-Galaxy** [jiewenhuang/halo-theme-joe3.0#311]
### 是什么版本出现了此问题？

 1.3.0

### 在线站点地址

https://blog.rising-galaxy.top/

### 发生了什么？

很多地方跟我的博客地址相关的都是: http://localhost:8090/ 这与我实际上的站点地址并不匹配。
- RSS 中的 link 部分
![image](https://github.com/user-attachments/assets/c801ee63-2067-4597-a06d-a6ff571dcc1e)
- 链接分享内容模版、自定义版权文案中的 {BlogUrl} 都是 http://localhost:8090/
- 默认许可协议文案中的 "本文链接" 部分，实际跳转链接倒是对了，但是显示的还是 http://localhost:8090/
![image](https://github.com/user-attachments/assets/e420d25d-eb85-4fe2-b645-e096628093ce)

**Comment by GuGuGee** [comment]
你的`docker-compose.yml`里面那个链接改成自己实际的博客地址了吗

**Comment by Rising-Galaxy** [comment]
> 你`docker-compose.yml`里面的链接改写了自己实际的博客地址了吗

我的问题，没改那个，我以为那个设置就是让它运行在本地然后通过 nginx 反代处理。
