### ISSUE TITLE
文章评论无法展示

### ISSUE THREAD

**Issue by lingdiansr** [jiewenhuang/halo-theme-joe3.0#317]
### 是什么版本出现了此问题？

 1.3.0

### 在线站点地址

https://lingdianshiren.xyz/archives/1717749908745

### 发生了什么？

文章评论无法展示，显示博主关闭了所有页面的评论，但是所有评论设置都为开启，更换其他主题可以展示
![image](https://github.com/user-attachments/assets/80fbb2ae-c84e-41ce-a1ce-faaf8090064e)
![image](https://github.com/user-attachments/assets/75d87b5e-3506-4911-aa27-c0f8cc94b844)
![image](https://github.com/user-attachments/assets/77457ff6-34e6-42f8-aa27-c6552c77529b)

### 相关日志输出

```shell
Halo日志文件
https://rec.lingdianshiren.xyz/%E8%BD%AF%E4%BB%B6/halo-log-2024-07-29%2018_58.log
```

### 附加信息

- 外部访问地址: https://lingdianshiren.xyz/
- 启动时间: 2024-07-29 18:28
- 版本: 2.17.2
- 构建时间: 2024-07-15 18:20
- Git Commit: aacd8c6
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-71-generic
- 已激活主题: [Theme Joe3 1.3.0](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [通知我 1.1.0](https://github.com/monyuan/notify-me)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [朋友圈 1.3.3](https://github.com/chengzhongxue/plugin-friends)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [静态网页服务 1.0.0-alpha.4](https://www.halo.run/store/apps/app-gFkMn)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Vditor 编辑器 1.7.1](https://github.com/justice2001/halo-plugin-vditor)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Docsme 1.0.0-alpha.7](https://www.halo.run/store/apps/app-yffxw)
  - [爱发电插件 1.6.3](https://github.com/carolcoral/plugin-afdian)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)

**Comment by jiewenhuang** [comment]
主题设置的，文章，还有其他设置各有一个th:if="${theme.config.other.enable_clean_mode == true} or ${theme.config.post.enable_comment !=true}"

**Comment by lingdiansr** [comment]
不好意思，是我打开了主题设置中其他设置的绿色模式，并非bug
我建议再设置页中标注出绿色模式所隐藏的组件，开关设置做对照容易遗留。
感谢您解决我的问题。

> 主题设置的，文章，还有其他设置各有一个th:if="${theme.config.other.enable_clean_mode == true} or ${theme.config.post.enable_comment !=true}"
