### ISSUE TITLE
页面可以修改么？改了一下友情链接。

### ISSUE THREAD

**Issue by gongpz** [jiewenhuang/halo-theme-joe3.0#32]
### 是什么版本出现了此问题？

2.8

### 在线站点地址

https://duangstar.com/links

### 发生了什么？

魔改了一下友情链接页面，喜欢这个模板，但是友情链接页面感觉不够简单，五颜六色，多姿多彩。
改完感觉跟肢体更搭了，作者见谅，过来给你汇报一下。
![0200](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68883149/58cff1f7-b92b-420b-a09c-f42d22eaa5a6)

**Comment by jiewenhuang** [comment]
可以，自己fork了之后改就行，不过你这个，错位了。
<img width="1475" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68629578/64772159-86cb-4f85-b71d-15a56791fa5b">
