### ISSUE TITLE
新增博主信息

### ISSUE THREAD

**Issue by ACZSHOP** [jiewenhuang/halo-theme-joe3.0#33]
### 你当前使用的版本

1.0.5

### 描述一下此特性

侧边栏的博主信息只有几个太少了，不如官方的Earth那么多选项。
![QQ图片20230821151922](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/142337549/176fbeec-e492-4f8a-b706-61e695c70363)

参考Earth主题（完全可以直接抄过来）。路径：侧边栏--社交媒体
![newius](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/142337549/ae6dec99-989c-4691-97f7-db3f3d5a55e6)

**Comment by dengchuanfu** [comment]
> 

也不支持自定义
