### ISSUE TITLE
图库图片加载问题

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#332]
### 是什么版本出现了此问题？

1.3.0

### 发生了什么？

图库加载是不是有问题？好像是按顺序加载的，比如分类1,2,3顺序加载，分类1没有加载完毕，点击分类2就会导致分类2的图片迟迟无法加载。

**Comment by jiewenhuang** [comment]
因为现在的数据并不是请求api（api现在不是共有权限）获取的，而是通过，前端过滤实现的，会导致有延迟
