### ISSUE TITLE
留言板显示全部评论在使用waline评论时不生效

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#335]
### 是什么版本出现了此问题？

1.4.0

### 发生了什么？

留言板显示全部评论在使用waline评论时不生效（默认评论不清楚），waline有加载全部评论的api吗？只找到了加载最近评论的api

**Comment by AR-26710** [comment]
只适配了自带评论（因为我只用Halo自带评论，所以就没考虑到三方评论🫢），现在没什么时间，可自行适配一下。

**Comment by AR-26710** [comment]
经过测试，使用waline没有加载全部评论的功能，只能加载某篇文章对应的评论列表，但是有获取当前网站的最近评论API`GET /api/comment?type=recent`，鉴于我waline评论过少，无法测得可以加载多少评论，有兴趣可自行进行测试对api更换后进行修改。

个人不建议使用，如果waline服务于多个网站则会将其他网站评论也加载进来。

附：[walineAPI](https://waline.js.org/reference/server/api.html)

**Comment by jiewenhuang** [comment]
waline的最新评论能获取到的应该是一百个，我记得我之前写的就是最大的一百。后面主题代码是不是改过，就不清楚了。
