### ISSUE TITLE
首页已运行时间不动，其他页面可以计时

### ISSUE THREAD

**Issue by dengchuanfu** [jiewenhuang/halo-theme-joe3.0#34]
### 是什么版本出现了此问题？

1.0.5

### 在线站点地址

https://www.ffbf.top/

### 发生了什么？

1.首页已运行时间不动，其他页面可以计时
2.瞬间-图片显示默认被百分百放大了且只能看见图片一部分除非点击下箭头，能不能像其它主题一样显示全部预览图。例如（https://ffbf.top/moments）
3.3D标签云一直显示“加载中。。。”

**Comment by jiewenhuang** [comment]
尝试清理一下反代缓存

**Comment by dengchuanfu** [comment]
友链申请格式是空白的

**Comment by jiewenhuang** [comment]
主题设置》友链有设置

**Comment by dengchuanfu** [comment]
友链设置，只有一个标题设置

**Comment by dengchuanfu** [comment]
> 尝试清理一下反代缓存

不行，重启halo也不行，换个主题又可以
