### ISSUE TITLE
如何设置默认的文章封面图？

### ISSUE THREAD

**Issue by Gabriel-six** [jiewenhuang/halo-theme-joe3.0#342]
### 你当前使用的版本

1.4.0

### 描述一下此特性

如何设置默认的文章封面图？或许可以考虑调用外部API来为没有手动设置封面的文章随机分配封面图，如调用必应的每日封面API；或者可选择由AI根据文章内容生成封面图。

**Comment by jiewenhuang** [comment]
默认封面和随机图，都是有的，自己设置找一下

**Comment by Gabriel-six** [comment]
> 默认封面和随机图，都是有的，自己设置找一下

您好，我找到了，在主题——基本设置里。开启随即图，并设置随机API。我用了这个apihttps://t.mwm.moe/pc，但是不知道为什么主题侧没有生效呢？对API格式有要求i吗，换了几个别的也没有显示。

**Comment by Gabriel-six** [comment]
> 默认封面和随机图，都是有的，自己设置找一下

您好，已解决。在主题——首页——文章默认缩略图，把这个设成与随即图一样的API即可。
