### ISSUE TITLE
文章打赏不生效

### ISSUE THREAD

**Issue by dengchuanfu** [jiewenhuang/halo-theme-joe3.0#36]
### 是什么版本出现了此问题？

joe3.0

### 在线站点地址

https://ffbf.top/

### 发生了什么？

后台开启了打赏功能，图片也设置了，一张二两都不行，没反应。
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/136884568/dc90ce0b-1c34-4948-811e-89a630e1bbc9)

**Comment by dengchuanfu** [comment]
把历史文章设置里面，把打赏设置“否”发布，再设置“是”发布才能显示出来打赏功能。

**Comment by devcui** [comment]
历史文章这个设置在哪里。。。

**Comment by dengchuanfu** [comment]
> 历史文章这个设置在哪里。。。

这个bug修复了，更新一下主题
在文章编辑的设置按钮里面
