### ISSUE TITLE
3D标签云无法显示，列表模式没有方格区分

### ISSUE THREAD

**Issue by Dion-Lee** [jiewenhuang/halo-theme-joe3.0#45]
### 是什么版本出现了此问题？

1.0.6

### 在线站点地址

http://halo.dlc.ink/

### 发生了什么？

<img width="342" alt="iShot_2023-08-25_18 23 07" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68332968/79c12b55-9fcc-4e47-a250-68ee2ac8a3f4">

3D标签云一直卡在“加载中...”

<img width="358" alt="iShot_2023-08-25_18 22 39" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68332968/e7a60e55-8df1-4b8f-9e76-974c6087933b">

列表标签云两个标签之间紧靠在一起，如上图linux和pve这两个标签紧挨在一起，无法区分
<img width="1547" alt="iShot_2023-08-25_18 23 34" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68332968/8aa8d00b-eb8a-4b6e-b0f0-fe4ec16a27b9">

**Comment by ldt0621** [comment]
我现在怀疑你的1.0.6版本上传错了，问题都在

**Comment by ldt0621** [comment]
<img width="402" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68332968/430e7f4a-17d0-47ed-a714-f4bf8fb6c25c">

文章页面头像不显示

**Comment by ldt0621** [comment]
写一下解决方法，3D标签云不显示，是因为标签宽度设置为了自适应宽度，改为固定宽度就好了，一个小Bug
<img width="705" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68332968/9e8a4909-60de-4f5c-9d3e-6dccc745459b">

文章页面头像，需要在用户--详情--点击头像上传，如果上传错误，是因为本地储存策略被删除，需要重启docker容器，默认储存策略会自动恢复，就可以正常上传了。算是halo的一个小Bug
