### ISSUE TITLE
毛玻璃导航效果问题

### ISSUE THREAD

**Issue by dengchuanfu** [jiewenhuang/halo-theme-joe3.0#47]
### 是什么版本出现了此问题？

1.0.6

### 在线站点地址

https://ffbf.top/

### 发生了什么？

设置毛玻璃导航效果后，只有”归档“和”友链“正常，其它页面导航条需要下滑才有效果。

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/136884568/33b7aa31-f8d3-4b96-8f18-71e5b3d0257e)

**Comment by ldt0621** [comment]
你看一下你的设置，我是都生效的
https://halo.dlc.ink/

**Comment by ldt0621** [comment]
有一个问题是一样的，无法识别出百度收录
<img width="195" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68332968/eb4f8e20-2cd9-48f0-ada0-5df39a650598">

**Comment by jiewenhuang** [comment]
> ### 是什么版本出现了此问题？
> 1.0.6
> 
> ### 在线站点地址
> https://ffbf.top/
> 
> ### 发生了什么？
> 设置毛玻璃导航效果后，只有”归档“和”友链“正常，其它页面导航条需要下滑才有效果。
> 
> ![image](https://user-images.githubusercontent.com/136884568/263445373-33b7aa31-f8d3-4b96-8f18-71e5b3d0257e.png)
> 
> ### 相关日志输出
> _No response_
> 
> ### 附加信息
> _No response_

这个设计就是这样，不是没生效，只是这个首页美化大图影响了，没有透上去，想要直接效果，也可以自己改一下

**Comment by dengchuanfu** [comment]
> 你看一下你的设置，我是都生效的 https://halo.dlc.ink/

你的也是要往上滑才能
