### ISSUE TITLE
主题颜色 设置无效，还是之前的颜色

### ISSUE THREAD

**Issue by Jehol1983** [jiewenhuang/halo-theme-joe3.0#49]
### 是什么版本出现了此问题？

最新

### 发生了什么？

主题颜色 设置无效，还是之前的颜色

**Comment by jiewenhuang** [comment]
具体？我这边测试都是没有问题的

**Comment by Jehol1983** [comment]
我把背景颜色换了，还是之前的颜色
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiewenhuang/halo-theme-joe3.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月27日(星期天) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiewenhuang/halo-theme-joe3.0] 主题颜色 设置无效，还是之前的颜色 (Issue #49)





 
具体？我这边测试都是没有问题的

**Comment by jiewenhuang** [comment]
截图具体修改了哪里

**Comment by Jehol1983** [comment]
就那两个，主题色（浅色）和 开启浅色模式背景图为是     改了这两个，改了没反应

**Comment by jiewenhuang** [comment]
那是背景图片，不是主题颜色，下个版本修
