### ISSUE TITLE
主题超级好，下个版本社交展示里面可以加个网易云音乐吗，跳转到网易云页面

### ISSUE THREAD

**Issue by Jehol1983** [jiewenhuang/halo-theme-joe3.0#51]
### 描述一下此特性

主题超级好，下个版本社交展示里面可以加个网易云音乐吗，跳转到网易云页面

**Comment by jiewenhuang** [comment]
现在可以自定义的喔

**Comment by Jehol1983** [comment]
请教下 在哪里啊，哈哈，只看到了可以侧边栏增加个 歌单id




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiewenhuang/halo-theme-joe3.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月27日(星期天) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiewenhuang/halo-theme-joe3.0] 主题超级好，下个版本社交展示里面可以加个网易云音乐吗，跳转到网易云页面 (Issue #51)





 
现在可以自定义的喔

**Comment by jiewenhuang** [comment]
主题设置》博主信息》社交信息来源》自定义

**Comment by Jehol1983** [comment]
感谢感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiewenhuang/halo-theme-joe3.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月27日(星期天) 晚上11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiewenhuang/halo-theme-joe3.0] 主题超级好，下个版本社交展示里面可以加个网易云音乐吗，跳转到网易云页面 (Issue #51)





 
主题设置》博主信息》社交信息来源》自定义
