### ISSUE TITLE
瞬间里面有评论，但是 不显示评论数量 

### ISSUE THREAD

**Issue by Jehol1983** [jiewenhuang/halo-theme-joe3.0#52]
### 是什么版本出现了此问题？

最新

### 发生了什么？

瞬间里面有评论，但是 不显示评论数量 

### 附加信息

<img width="355" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/75714146/3c9fca8c-5202-4794-8c8c-f9b3b0bb362e">

**Comment by jiewenhuang** [comment]
刷新一下
