### ISSUE TITLE
文章目录点击跳转错误

### ISSUE THREAD

**Issue by Dion-Lee** [jiewenhuang/halo-theme-joe3.0#55]
### 是什么版本出现了此问题？

1.0.7

### 在线站点地址

https://halo.dlc.ink/archives/joe3.0

### 发生了什么？

点击文章目录不能跳到相对应的内容页面，而是直接跳到页面顶端

https://github.com/jiewenhuang/halo-theme-joe3.0/assets/68332968/315e5065-dc63-44f7-bfff-28fd89fa001d

**Comment by jiewenhuang** [comment]
自行给标题添加id

**Comment by renshinizhenhao** [comment]
我也遇到的这个问题。你现在解决了吗？

**Comment by renshinizhenhao** [comment]
> 自行给标题添加ID

自行给标题添加id是什么意思？怎么添加？

**Comment by renshinizhenhao** [comment]
> 自行给标题添加id

刚刚找到了给标题加id的书写格式<h2 id="header-id">Header</h2>
还有没有更简单的书写格式？

**Comment by renshinizhenhao** [comment]
> 自行给标题添加id

刚刚找到了给标题加id的书写格式“<h2 id="header-id">Header</h2>”
还有没有更简单的书写格式？

**Comment by renshinizhenhao** [comment]
> 自行给标题添加id

刚刚找到了给标题加id的书写格式
```
<h2 id="header-id">Header</h2>
```
还有没有更简单的书写格式？

**Comment by Dion-Lee** [comment]
> > 自行给标题添加id
> 
> 刚刚找到了给标题加id的书写格式
> 
> ```
> <h2 id="header-id">Header</h2>
> ```
> 
> 还有没有更简单的书写格式？

我也没好的解决方法
