### ISSUE TITLE
夜间模式的评论样式未完全适配

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#56]
### 是什么版本出现了此问题？

1.0

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/dd755885-ab8a-47fa-9465-768f47930c23)
一些用户以及其他一些字体的颜色是黑色的在夜间模式看不到

**Comment by jiewenhuang** [comment]
更新版本，刷新切换颜色后刷新一下就出来了

**Comment by Einstein-schrodinger** [comment]
也就是切换完夜间或白天模式都需要手动刷新一下

**Comment by Einstein-schrodinger** [comment]
> 更新版本，刷新切换颜色后刷新一下就出来了
https://github.com/halo-sigs/plugin-comment-widget/issues/56
