### ISSUE TITLE
夜晚模式评论区看不见

### ISSUE THREAD

**Issue by dengchuanfu** [jiewenhuang/halo-theme-joe3.0#59]
### 是什么版本出现了此问题？

1.0.8

### 在线站点地址

https://ffbf.top/

### 发生了什么？

rt，切换之后看不清，要刷新一下才能看清

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/136884568/fab2f6d4-eb29-4545-a0d2-b9a867f48751)

**Comment by jiewenhuang** [comment]
这应该是插件的问题
