### ISSUE TITLE
黑夜模式没变黑

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#61]
### 是什么版本出现了此问题？

1.0.8

### 发生了什么？

如图中红框所示，开启黑夜模式依然是白色
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/218a8297-8f5d-4fad-b04c-e3a5bafed30e)

**Comment by Einstein-schrodinger** [comment]
分类、标签、友链等页面也是如此

**Comment by jiewenhuang** [comment]
那应该是什么颜色，黑色？

**Comment by Einstein-schrodinger** [comment]
> 那应该是什么颜色，黑色？

对
