### ISSUE TITLE
在后台添加备案号前台不显示

### ISSUE THREAD

**Issue by wleelw** [jiewenhuang/halo-theme-joe3.0#67]
### 是什么版本出现了此问题？

1.0.8

### 在线站点地址

https://bb.sondy.top/

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/74389842/71f00f07-602e-4ee7-bd9f-b96723c67d4a)
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/74389842/c9658879-44d0-4d4a-88ec-40ee8f5c68e1)

**Comment by ACZSHOP** [comment]
你的站点已经显示ICP备案号了![4K{(I0 X_A(UXST~Y~N81 A](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/142337549/29edc8b8-22ed-49b0-bc44-b0ddbc36bbce)

在主题的-（基本设置）里面配置备案信息，然后在 （页脚 ）配置显示开关
