### ISSUE TITLE
为什么我的控制台会一直访问一言的API

### ISSUE THREAD

**Issue by Lyn4ever29** [jiewenhuang/halo-theme-joe3.0#68]
### 是什么版本出现了此问题？

1.0.8

### 在线站点地址

https://jhacker.cn

### 发生了什么？

如图，为什么一直访问一言api
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/25952589/c4c8a157-2ca9-4e3b-8760-5d5be0fbefb7)

**Comment by emanjusaka** [comment]
引入beauty.min.js时是否应该加个判断，目前好像只有开启顶部大图时会用到一言。目前即使没开顶部大图也引入了beauty.min.js，它里面执行了延时循环调用一言API的方法。
