### ISSUE TITLE
友情链接 分组 ，第一行 可以去掉吗

### ISSUE THREAD

**Issue by cosolar** [jiewenhuang/halo-theme-joe3.0#74]
### 是什么版本出现了此问题？

1.0.9

### 发生了什么？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/28598727/6a31a6dd-c1d8-4886-807e-8390f1e5ea04)
能把去掉吧

### 附加信息

友情链接 能不能界面优化一下

**Comment by jiewenhuang** [comment]
这是插件遗留问题，不是主题的问题。

**Comment by hejaya** [comment]
可以去改下links.html 过滤掉，它默认有个全部主题
th:each="group : ${groups.?[spec.displayName != '']}"
