### ISSUE TITLE
v1.1.0版本，友链无法识别全部分组中的链接

### ISSUE THREAD

**Issue by wanrenbuwanxin** [jiewenhuang/halo-theme-joe3.0#81]
### 是什么版本出现了此问题？

v1.1.0

### 在线站点地址

http://wscsmile.x3322.net:8090/

### 发生了什么？

v1.1.0版本，友链无法识别全部分组中的链接，必须要新建分组后才能识别。

**Comment by jiewenhuang** [comment]
友链页设计就是按照分组显示的，只想显示一个，可以把所有链接都加到一个分组，或者自定fork代码修改
