### ISSUE TITLE
关于精品分类的展示问题

### ISSUE THREAD

**Issue by Sakura-LF** [jiewenhuang/halo-theme-joe3.0#82]
### 是什么版本出现了此问题？

最新版

### 在线站点地址

https://www.sakurasss.top

### 发生了什么？

# 精品分类达到二层时 , 图片的上下边距过小
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/80140609/e169d11b-98d0-492f-880f-70463c5c8328)

**Comment by jiewenhuang** [comment]
这个原本应该是只显示四个来着

**Comment by Sakura-LF** [comment]
大佬那能改成八个嘛 &#x1F600;
还有大佬那个默认显示 TOC 层级的设置没用 , 是因为我用的是默认编辑器嘛 
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/80140609/3c3e63bf-68a7-42d0-85e0-baef5d47c2b4)
