### ISSUE TITLE
瞬时页面，头像附近不显示昵称

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#84]
### 是什么版本出现了此问题？

1.10.0

### 发生了什么？

瞬时页面，头像附近不显示昵称，如图所示
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/b4b5348f-2f02-43be-a229-6d7e853fccf0)

**Comment by yundabei** [comment]
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/34499405/6246677d-1627-42b3-b0ed-56ebc23c6dac)
https://github.com/jiewenhuang/halo-theme-joe3.0/pull/152
