### ISSUE TITLE
能不依赖katex插件实现公式渲染吗

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#85]
### 你当前使用的版本

1.10.0

### 描述一下此特性

用了katex插件就不能使用Tool-Bench插件，能解决这个矛盾吗（Tool-Bench作者说是由于渲染冲突导致的）
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/45d84e7c-f98c-49a3-a492-0d90b2f7207c)

**Comment by wxyShine** [comment]
可以 插件和主题都把这个功能做成开关

**Comment by jiewenhuang** [comment]
用tool后，好像数学公式直接被识别文文本了，DOM都没了

**Comment by jiewenhuang** [comment]
这边建议卸载军刀使用vditor编辑器，现在配合joe的最优解
