### ISSUE TITLE
图库能不能改进一下

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#86]
### 你当前使用的版本

1.10.0

### 描述一下此特性

应用市场的图库插件均是三个图片为一行，导致留有较多的空白（如图所示），十分不美观
![image](https://github.com/halo-sigs/plugin-photos/assets/62790820/cddd826b-1524-4cae-b9f4-1b5cf7f505c5)
能否如下图中的相册所示进行适配，而非固定的三个图片一行，像Joe2.0的图库那种
![image](https://github.com/halo-sigs/plugin-photos/assets/62790820/a180d66c-c26c-4dc3-a7e5-7b67997c41cd)

**Comment by bluezsd** [comment]
这个应该是联系图库插件的作者处理吧？主题只是调用插件
