### ISSUE TITLE
友链中网站名称显示不全

### ISSUE THREAD

**Issue by wanrenbuwanxin** [jiewenhuang/halo-theme-joe3.0#91]
### 你当前使用的版本

v1.1.0

### 描述一下此特性

友链中网站名称显示不全

### 附加信息

![微信截图_20230917031013](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/27992177/8ea1507d-bce5-4e32-8ab0-4f0f470f2aa3)

**Comment by jiewenhuang** [comment]
自己检查下是不是修改过什么，或者添加过其他css影响了，这边用的是没有问题的

**Comment by jiewenhuang** [comment]
描述内容填多一点就能撑出来了

**Comment by duanluan** [comment]
我也发现了，1.1.4 也是这样，倒数第二个是“百度”，都能忽略掉。
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/14957667/b2316709-e54d-4c81-8f84-1e60130ddf6c)
而且我还在 1.1.3 更新到 1.1.4 之后出现了友链“全部”分组里面的没法显示的问题，我就新建了一个分组。

**Comment by duanluan** [comment]
> 友链中网站名称显示不全

**设置**-**代码注入**-**全局 head 标签**
```js
<script>
  /* 解决友链名称显示不全 */
  $(()=>{ $('.evan-friends .title').css('max-width','none') })
</script>
```
