### ISSUE TITLE
真心希望文章标题书写不需要标题id

### ISSUE THREAD

**Issue by renshinizhenhao** [jiewenhuang/halo-theme-joe3.0#92]
### 你当前使用的版本

3.0

### 描述一下此特性

真心希望文章目录的跳转，标题书写不需要标题id。这样书写太麻烦了。我在obsidian上书写还不能折叠了。

**Comment by jiewenhuang** [comment]
这是编辑器该做的处理，主题端不做处理，默认编辑器不会出现这个问题

**Comment by jiewenhuang** [comment]
插件更新下最新版https://github.com/DioxideCN/Tool-Bench/releases/tag/v1.0.4-ea

**Comment by renshinizhenhao** [comment]
大佬！首先谢谢你的回复。
我更新了你提供的插件。
迫不及待的弄了一篇文章去试一试，发现滚动文章，文章目录也轮动了。
点击左侧的文章目录，也能快速的到达指定标题。
但仅仅只限于h1级别的标题，h2及以下的标题还是不行，点击之后还是无法跳转。




ゞ牁懓啲ヅ伱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiewenhuang/halo-theme-joe3.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月17日(星期天) 晚上8:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiewenhuang/halo-theme-joe3.0] 真心希望文章标题书写不需要标题id (Issue #92)





 
插件更新下最新版https://github.com/DioxideCN/Tool-Bench/releases/tag/v1.0.4-ea

**Comment by jiewenhuang** [comment]
有没有可能是你标题离得太近，都在一个页面内
